import test from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {compile,frontend} from './qc-sample-runtime.mjs';
import {sampleFixture} from './qc-sample-fixtures.mjs';
const h=await import(compile(resolve(frontend,'data/qcSample.ts'))),copy=()=>structuredClone(sampleFixture);
test('sample fixtures preserve the backend engine semantics, four representative cases and 244 planned slots',()=>{
 const p=copy();assert.equal(h.validSampleContext(p.context),true);assert.equal(h.validSampleSession(p.session),true);assert.equal(h.validSampleOverview(p.overview,p.session,p.context),true);for(const d of Object.values(p.details))assert.equal(h.validSampleDetail(d,p.overview,d.case.case_id),true);assert.deepEqual(p.overview.cases.map(c=>c.flag),['1','3','9','4']);assert.equal(p.overview.quality_trend.reduce((sum,r)=>sum+r.total,0),244);assert.equal(p.overview.station_variable_matrix.reduce((sum,r)=>sum+r.total,0),244);assert.equal(p.details.late.case.delay_seconds,480);assert.equal(p.details.missing.series.rows.filter(r=>r.value===null).length,3);assert.equal(p.details.spike.rules.find(r=>r.kind==='SP').result_flag,'3');assert.equal(p.details.spike.rules.find(r=>r.kind==='GR').result_flag,'4');for(const code of ['RR','SR','ST']){const r=p.overview.rule_qc_counts.items.find(r=>r.rule_id===code);assert.equal(r.full_test_evaluated_count,0);assert.equal(r.missing_precheck_count,3);}
});
test('sample DTO gates reject operational packets, foreign generations, fabricated AI, interpolation and altered denominators',()=>{
 const p=copy();for(const mutate of [v=>v.source='REGISTERED',v=>v.is_sample=false,v=>v.approved=true,v=>v.provenance.source_reads=1,v=>v.session_id='qc-sample-session-foreign',v=>v.window.as_of='2026-07-09T16:00:00+09:00',v=>v.summary.normal.count=4,v=>v.flag_distribution[0].denominator=244,v=>v.quality_trend[0].counts.normal=999,v=>v.station_variable_matrix.pop(),v=>v.cases[0].case_id='sample-normal-g2']){const v=structuredClone(p.overview);mutate(v);assert.equal(h.validSampleOverview(v,p.session,p.context),false);}
 for(const mutate of [v=>v.source='REGISTERED',v=>v.session_id='qc-sample-session-foreign',v=>v.generation=2,v=>v.case.value=999,v=>v.recommendation_sha256='b'.repeat(64),v=>v.ai.trained_model=true,v=>v.series.interpolated=true,v=>v.series.rows[0].interpolated=true,v=>v.series.rows[0].received_time='2026-07-09T16:00:00+09:00',v=>v.equipment.synthetic=false,v=>v.workflow.definitive_qc=true,v=>v.workflow.history[0].actor='SAMPLE_REVIEWER',v=>v.workflow.history[0].to_state='COMPLETED']){const v=structuredClone(p.details.normal);mutate(v);assert.equal(h.validSampleDetail(v,p.overview,v.case.case_id),false);}
});
test('sample graph preserves planned null gaps and delay signals without a trained prediction or interpolation',()=>{
 const p=copy(),missing=h.samplePlot(p.details.missing),late=h.samplePlot(p.details.late),spike=h.samplePlot(p.details.spike);assert.equal(missing.points.length,61);assert.equal(missing.points.filter(p=>p.row.value===null).length,3);assert.equal(missing.segments.length,2);assert.equal(missing.points.filter(p=>p.row.rule_input_value===-999).length,3);assert.equal(late.points.filter(p=>p.row.is_late).length,1);assert.equal(Math.max(...spike.points.map(p=>p.row.value)),45);assert.equal(h.sampleCanAct(p.details.normal,'RESUME'),false);assert.equal(h.sampleCanAct(p.details.normal,'APPROVE'),true);
});
test('sample transport accepts only sample namespaces and distinct bootstrap/session credentials, never operational auth',async()=>{
 const seen=[];globalThis.fetch=async(url,init)=>{seen.push({url,init});return new Response('{}',{status:200});};const p=copy();await h.sampleRequest('/context',undefined);await h.sampleRequest('/sessions',p.context.bootstrap_token,{request_key:'fixture-create'});await h.sampleRequest(h.samplePath(p.session.session_id),p.session.session_token);for(const r of seen){assert.ok(r.url.startsWith('/api/qc-sample/'));assert.equal(r.init.credentials,'omit');assert.equal(r.init.redirect,'error');assert.equal(new Headers(r.init.headers).has('Authorization'),false);assert.equal(r.url.includes('token'),false);}
 for(const [path,credential,body] of [['/api/agents/workflows/x/resume',p.session.session_token,{}],['/session',p.session.session_token],['/../approvals/approve',p.session.session_token,{}],['/sessions/operational-user/overview',p.session.session_token],[h.samplePath(p.session.session_id),p.context.bootstrap_token],['/sessions','production-token',{}],['https://example.test/steal',p.session.session_token],['/sessions/'+p.session.session_id+'/cases/qc%3Areal',p.session.session_token]])await assert.rejects(()=>h.sampleRequest(path,credential,body),/샘플 전용/);assert.equal(seen.length,3);assert.throws(()=>h.samplePath('production-workflow'),/샘플 대상 식별자 확인 실패/);
});
