import test from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {Window} from 'happy-dom';
import {compile,frontend} from './qc-sample-runtime.mjs';
import {sampleFixture} from './qc-sample-fixtures.mjs';

const win=new Window({url:'http://localhost/qc/sample'});
for(const key of ['window','document','HTMLElement','SVGElement','Element','Node','MouseEvent','KeyboardEvent','Event','CustomEvent','MutationObserver'])globalThis[key]=key==='window'?win:win[key];Object.defineProperty(globalThis,'navigator',{value:win.navigator,configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const React=await import('react'),{act}=React,{createRoot}=await import('react-dom/client'),{MemoryRouter}=await import('react-router-dom'),Page=(await import(compile(resolve(frontend,'pages/QCSample.tsx')))).default;
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
let root,container,requests;
function apiFixture(){
 const f=structuredClone(sampleFixture),store=f.details,receipt=f.session;let overrideReview,overrideDetail;
 const setCapabilities=d=>{const state=d.workflow.status;d.workflow.capabilities={comment:true,approve:['PENDING','HELD'].includes(state),hold:['PENDING','APPROVED'].includes(state),reject:['PENDING','HELD','APPROVED'].includes(state),resume:state==='APPROVED'};};
 const detail=scenario=>{const d=structuredClone(store[scenario]);d.session_revision=receipt.session_revision;return d;};
 const overview=()=>{const p=structuredClone(f.overview);p.session_revision=receipt.session_revision;p.generation=receipt.generation;p.cases=Object.values(store).map(d=>structuredClone(d.case));p.review_queue={rows:structuredClone(p.cases),total:4};for(const [metric,state] of [['pending','PENDING'],['completed','COMPLETED']]){const count=p.cases.filter(c=>c.review_status===state).length;p.summary[metric].count=count;p.summary[metric].rate=count*25;}return p;};
 const apply=(scenario,action,comment)=>{const d=store[scenario],from=d.workflow.status,clock=d.window.as_of;const add=(action,from_state,to_state,actor,comment)=>d.workflow.history.push({sequence:d.workflow.history.length+1,action,from_state,to_state,actor,comment,sample_clock:clock});const to=({COMMENT:from,HOLD:'HELD',REJECT:'REJECTED',APPROVE:'APPROVED',RESUME:'COMPLETED'})[action];if(action==='RESUME'){add('RESUME',from,'RESUMING','SAMPLE_REVIEWER',comment);add('COMPLETE_SAMPLE_DRAFT','RESUMING','COMPLETED','SAMPLE_ENGINE','승인 후 샘플 초안 단계 완료');}else add(action,from,to,'SAMPLE_REVIEWER',comment);d.case.review_status=d.workflow.status=to;d.workflow.blocked=to!=='COMPLETED';d.workflow.downstream_executed=to==='COMPLETED';d.case.revision=d.workflow.revision=++d.revision;receipt.session_revision++;setCapabilities(d);return detail(scenario);};
 const respond=async(url,init)=>{assert.ok(url.startsWith('/api/qc-sample/'),'sample must never call operational namespaces');assert.equal(init.credentials,'omit');assert.equal(new Headers(init.headers).has('Authorization'),false);const path=url.slice('/api/qc-sample'.length);if(path==='/context')return json(f.context);if(path==='/sessions')return json(receipt);if(path.endsWith('/overview'))return json(overview());if(path.endsWith('/reset')){const body=JSON.parse(init.body);assert.equal(body.expected_session_revision,receipt.session_revision);receipt.session_revision++;receipt.generation++;for(const scenario of Object.keys(store)){const original=structuredClone(sampleFixture.details[scenario]);store[scenario]=original;original.generation=receipt.generation;original.case.case_id='sample-'+scenario+'-g'+receipt.generation;original.recommendation_sha256=original.case.recommendation_sha256=original.workflow.recommendation_sha256=({normal:'b',late:'c',missing:'d',spike:'e'})[scenario].repeat(64);}return json(receipt);}const match=/\/cases\/sample-(normal|late|missing|spike)-g\d+(\/review)?$/.exec(path);assert.ok(match,'only known sample case endpoints are allowed');const scenario=match[1];if(match[2]){const body=JSON.parse(init.body);if(overrideReview)return overrideReview(scenario,body,apply);assert.equal(body.expected_revision,store[scenario].revision);assert.equal(body.recommendation_sha256,store[scenario].recommendation_sha256);assert.ok(body.request_key);assert.ok(body.comment.trim());return json(apply(scenario,body.action,body.comment));}return overrideDetail?overrideDetail(scenario,detail):json(detail(scenario));};
 return {respond,detail,overview,apply,setReview:fn=>overrideReview=fn,setDetail:fn=>overrideDetail=fn,receipt};
}
async function flush(){await act(async()=>{await new Promise(r=>setTimeout(r,10));});}
async function mount(api){requests=[];globalThis.fetch=async(input,init={})=>{requests.push({url:String(input),init});return api.respond(String(input),init);};container=document.createElement('div');document.body.append(container);root=createRoot(container);await act(async()=>{root.render(React.createElement(MemoryRouter,{initialEntries:['/qc/sample']},React.createElement(Page)));await new Promise(r=>setTimeout(r,10));});await flush();}
async function dispose(){if(root)await act(async()=>root.unmount());container?.remove();root=null;await win.happyDOM.waitUntilComplete();}
const button=text=>[...container.querySelectorAll('button')].find(b=>b.textContent.trim()===text),label=text=>container.querySelector(`[aria-label="${text}"]`);
async function click(node){assert.ok(node);await act(async()=>{node.dispatchEvent(new MouseEvent('click',{bubbles:true}));await new Promise(r=>setTimeout(r,10));});await flush();}
async function choose(scenario){const sc=sampleFixture.context.scenario_catalog.find(c=>c.scenario_id===scenario);await click(label(sc.label+' 샘플 상세검토'));}
async function comment(value){const node=label('샘플 검토 의견');assert.ok(node);await act(async()=>{Object.getOwnPropertyDescriptor(Object.getPrototypeOf(node),'value').set.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));});}

test('React sample boots its own session, shows all four scenarios, denominator units and persistent sample boundary banners',async()=>{
 try{await mount(apiFixture());assert.equal(container.querySelectorAll('.qs-shortcuts button').length,4);assert.equal(container.querySelectorAll('.qs-metrics article').length,6);assert.equal(container.querySelectorAll('.qs-metrics article p').length,6);for(const p of container.querySelectorAll('.qs-metrics article p'))assert.match(p.textContent,/대표 사례 4건 기준/);assert.match(container.textContent,/샘플 예정 슬롯/);assert.equal(container.querySelector('a').getAttribute('href'),'/qc?data_mode=LIVE&source=REGISTERED');assert.equal(requests.length,3);await choose('normal');assert.equal(container.querySelectorAll('.qs-banner').length,2);assert.equal(container.querySelector('[role="dialog"]').getAttribute('aria-modal'),'true');assert.match(container.querySelector('.qs-detail-facts').textContent,/정상 \(1\)/);assert.equal(button('샘플 후속 단계 재개').disabled,true);assert.match(container.textContent,/AI 분석 미실행/);assert.match(container.querySelector('.qs-history').textContent,/샘플 엔진/);assert.equal(container.textContent.includes(sampleFixture.session.session_token),false);assert.equal(win.localStorage.length,0);assert.equal(win.sessionStorage.length,0);for(const r of requests){assert.ok(r.url.startsWith('/api/qc-sample/'));assert.equal(new Headers(r.init.headers).has('Authorization'),false);}
 }finally{await dispose();}
});
test('React late, missing and spike sample details show calculated Rule evidence, null gaps and precise values',async()=>{
 try{await mount(apiFixture());await choose('late');assert.equal(container.querySelectorAll('.qs-late-marker').length,1);assert.match(container.querySelector('.qs-detail-facts').textContent,/8분/);const de=[...container.querySelectorAll('.qs-detail-rules tbody tr')].find(r=>r.querySelector('th').textContent==='DE');assert.match(de.textContent,/300/);assert.match(de.textContent,/주의.*\(3\)/);await click(label('샘플 상세 닫기'));await choose('missing');assert.equal(container.querySelectorAll('.qs-missing-slot').length,3);assert.equal(container.querySelectorAll('.qs-observed-line').length,2);assert.match(container.textContent,/61 예정 슬롯 · 수신 58 · 결측 3/);assert.match(container.querySelector('.qs-detail-rules').textContent,/결측 선검사 · 본 검사 실행 아님/);assert.equal(container.querySelectorAll('.qs-detail-series tbody tr').length,61);assert.equal([...container.querySelectorAll('.qs-detail-series tbody tr')].filter(r=>r.textContent.includes('-999')).length,3);await click(label('샘플 상세 닫기'));await choose('spike');assert.match(container.querySelector('.qs-detail-facts').textContent,/45 degree_C/);const rows=[...container.querySelectorAll('.qs-detail-rules tbody tr')],sp=rows.find(r=>r.querySelector('th').textContent==='SP'),gr=rows.find(r=>r.querySelector('th').textContent==='GR');assert.match(sp.textContent,/주의.*\(3\)/);assert.match(gr.textContent,/BAD \(4\)/);assert.match(container.querySelector('.qs-rule-list').textContent,/결측 선검사 3건/);assert.match(container.querySelector('.qs-rule-list').textContent,/본 검사 미실행/);
 }finally{await dispose();}
});
test('React sample comments, hold, approve and resume increment revisions and run only the sample downstream stage',async()=>{
 try{await mount(apiFixture());await choose('normal');await click(button('샘플 승인'));assert.equal(requests.filter(r=>r.url.endsWith('/review')).length,0);assert.match(container.textContent,/1~2000자/);for(const [action,expected] of [['검토 의견 저장','PENDING'],['검토 보류','HELD'],['샘플 승인','APPROVED'],['샘플 후속 단계 재개','COMPLETED']]){await comment('격리된 샘플 근거를 확인했습니다: '+expected);await click(button(action));assert.match(container.querySelector('.qs-gate-state').textContent,new RegExp(expected==='COMPLETED'?'샘플 처리 완료':expected==='APPROVED'?'샘플 승인 · 재개 대기':expected==='HELD'?'검토 보류':'검토 대기'));if(expected==='APPROVED'){assert.match(container.querySelector('.qs-gate-state').textContent,/후속 단계 중지/);assert.equal(button('샘플 후속 단계 재개').disabled,false);}}
 const posts=requests.filter(r=>r.url.endsWith('/review'));assert.deepEqual(posts.map(r=>JSON.parse(r.init.body).expected_revision),[1,2,3,4]);assert.match(container.querySelector('.qs-history').textContent,/COMPLETE_SAMPLE_DRAFT · 샘플 엔진/);assert.equal(button('샘플 승인').disabled,true);assert.equal(button('샘플 후속 단계 재개').disabled,true);assert.match(container.querySelector('.qs-metrics article:last-child').textContent,/1건/);assert.equal(posts.every(r=>r.url.startsWith('/api/qc-sample/')),true);
 }finally{await dispose();}
});
test('React rejecting a sample blocks resume and refreshes its independent case status',async()=>{
 try{await mount(apiFixture());await choose('spike');await comment('이 가상 사례는 샘플 반려입니다.');await click(button('샘플 반려'));assert.match(container.querySelector('.qs-gate-state').textContent,/샘플 반려 · 후속 단계 차단/);assert.equal(button('샘플 후속 단계 재개').disabled,true);assert.equal(button('샘플 승인').disabled,true);assert.match(container.querySelector('.qs-history').textContent,/REJECT/);assert.equal(requests.filter(r=>r.url.endsWith('/review')).length,1);
 }finally{await dispose();}
});
test('React stale sample revision returns a visible conflict and refreshes before another deliberate review',async()=>{
 const api=apiFixture();let once=true;api.setReview((scenario,body,apply)=>{if(once){once=false;apply(scenario,'COMMENT','다른 샘플 검토 창에서 추가한 의견');return json({detail:'SAMPLE_STALE_REVISION'},409);}return json(apply(scenario,body.action,body.comment));});try{await mount(api);await choose('late');await comment('가상 수신 지연 확인');await click(button('샘플 승인'));assert.match(container.textContent,/SAMPLE_STALE_REVISION.*HTTP 409/);assert.match(container.querySelector('.qs-gate-state').textContent,/revision 2/);assert.equal(requests.filter(r=>r.url.endsWith('/review')).length,1);await comment('갱신된 샘플 이력을 확인했습니다.');await click(button('샘플 승인'));assert.equal(JSON.parse(requests.filter(r=>r.url.endsWith('/review')).at(-1).init.body).expected_revision,2);assert.match(container.querySelector('.qs-gate-state').textContent,/샘플 승인 · 재개 대기/);
 }finally{await dispose();}
});
test('React double-click review sends one mutation and reset replaces the sample generation without preserving old selections',async()=>{
 try{await mount(apiFixture());await choose('normal');await comment('중복 클릭에도 한 번만 샘플 승인합니다.');const approve=button('샘플 승인');await act(async()=>{approve.dispatchEvent(new MouseEvent('click',{bubbles:true}));approve.dispatchEvent(new MouseEvent('click',{bubbles:true}));await new Promise(r=>setTimeout(r,10));});await flush();assert.equal(requests.filter(r=>r.url.endsWith('/review')).length,1);await click(label('샘플 상세 닫기'));await click(button('샘플 초기화'));assert.match(container.querySelector('.qs-time').textContent,/generation 2/);assert.equal(container.querySelector('[role="dialog"]'),null);assert.match(container.querySelector('.qs-metrics article:nth-last-child(2)').textContent,/4건/);await choose('missing');assert.equal(requests.at(-1).url.endsWith('/cases/sample-missing-g2'),true);assert.match(container.querySelector('.qs-gate-state').textContent,/revision 1/);assert.equal(button('샘플 후속 단계 재개').disabled,true);
 }finally{await dispose();}
});
test('React altered sample authority cannot display a graph or enable review and can be retried safely',async()=>{
 const api=apiFixture();api.setDetail((scenario,detail)=>{const d=detail(scenario);d.source='REGISTERED';return json(d);});try{await mount(api);await choose('normal');assert.match(container.textContent,/근거 확인 실패/);assert.equal(container.querySelectorAll('.qs-series').length,0);assert.equal(button('샘플 승인'),undefined);api.setDetail(undefined);await click(button('샘플 상세 다시 조회'));assert.equal(container.querySelectorAll('.qs-series').length,1);assert.equal(button('샘플 후속 단계 재개').disabled,true);
 }finally{await dispose();}
});
test('React switching sample cases aborts an old detail response so it cannot appear under the new scenario',async()=>{
 const api=apiFixture();let release;api.setDetail((scenario,detail)=>scenario==='normal'?new Promise(resolve=>release=()=>resolve(json(detail(scenario)))):json(detail(scenario)));try{await mount(api);await choose('normal');assert.match(container.querySelector('[role="dialog"]').textContent,/조회하고 있습니다/);await click(label('샘플 상세 닫기'));await choose('late');assert.match(container.querySelector('.qs-detail-facts').textContent,/8분/);await act(async()=>release());await flush();assert.match(container.querySelector('.qs-detail-facts').textContent,/8분/);assert.equal(container.querySelector('.qs-drawer h2').textContent.includes('수신 지연'),true);
 }finally{await dispose();}
});
test('React sample refresh synchronously blocks an old same-tick review until fresh evidence is loaded',async()=>{
 const api=apiFixture(),original=api.respond;let waiting=false,release;api.respond=(url,init)=>waiting&&url.endsWith('/overview')?new Promise(resolve=>release=()=>{waiting=false;resolve(original(url,init));}):original(url,init);
 try{await mount(api);await choose('spike');const ticks=[...container.querySelectorAll('.qs-axis-tick')];assert.equal(ticks.length,3);for(const tick of ticks){const display=[...tick.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent).join('');assert.match(display,/^-?[\d,]+(?:\.\d)?$/);assert.ok(tick.querySelector('title'),'axis tick retains its precise value in the tooltip');}assert.match(container.querySelector('.qs-detail-facts').textContent,/45 degree_C/);
 await comment('새로고침한 근거가 도착한 뒤에 승인합니다.');const approve=button('샘플 승인'),refresh=button('샘플 새로고침');waiting=true;await act(async()=>{refresh.dispatchEvent(new MouseEvent('click',{bubbles:true}));approve.dispatchEvent(new MouseEvent('click',{bubbles:true}));await new Promise(r=>setTimeout(r,10));});assert.equal(requests.filter(r=>r.url.endsWith('/review')).length,0);assert.equal(button('샘플 승인').disabled,true);await act(async()=>release());await flush();assert.equal(button('샘플 승인').disabled,false);await comment('새 근거를 확인했고 샘플 승인을 진행합니다.');await click(button('샘플 승인'));assert.equal(requests.filter(r=>r.url.endsWith('/review')).length,1);assert.match(container.querySelector('.qs-gate-state').textContent,/샘플 승인 · 재개 대기/);
 }finally{if(waiting&&release)release();await dispose();}
});
