import StationClassifications, { DatasetSourceSelect } from './StationClassifications';
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { MapContainer, CircleMarker, Popup } from 'react-leaflet';
import { Settings, Wrench, CalendarDays, ShieldCheck, RefreshCw } from 'lucide-react';
import 'leaflet/dist/leaflet.css';
import OSMBaseLayer from './OSMBaseLayer';
import { API_BASE_URL, apiFetch } from '../api/client';

const panel='bg-white border border-blue-100 rounded-2xl p-5 shadow-sm min-w-0';
const fmt=(n:any)=>n==null?'미확정':Number(n).toLocaleString('ko-KR');
function Citation({row}:{row:any}) {return <details className="text-xs mt-2"><summary className="text-blue-700 cursor-pointer">원문 근거</summary><p className="whitespace-pre-wrap mt-2">{row.excerpt}</p><p className="mt-2 text-slate-500">{row.locator}</p><p className="break-all text-slate-500 mt-1">{row.path}</p><p className="break-all text-[10px] text-slate-400 mt-1">SHA-256: {row.sha256}</p></details>;}

export default function EquipmentWorkspace() {
  const [search,setSearch]=useSearchParams();
  const source=search.get('source')||'GD_OBS_ST_MONTHLY',from=search.get('from')||(source==='HISTORICAL_RECONCILED'?'2011-01':'2023-01'),to=search.get('to')||(source==='HISTORICAL_RECONCILED'?'2021-12':'2026-07');
  const station=search.get('station')||'';
  const update=(v:Record<string,string>)=>setSearch({...Object.fromEntries(search),...v});
  const baseQuery=new URLSearchParams({network:search.get('network')||'',sea:search.get('sea')||'',source,from_month:from,to_month:to}).toString();
  const query=new URLSearchParams({network:search.get('network')||'',sea:search.get('sea')||'',source,from_month:from,to_month:to,station}).toString();
  const linkQuery=new URLSearchParams({network:search.get('network')||'',sea:search.get('sea')||'',source,from,to}).toString();
  const [data,setData]=useState<any>(null),[overview,setOverview]=useState<any>(null),[refs,setRefs]=useState<any[]>([]);
  const [error,setError]=useState(''),[refError,setRefError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0);
  const [keyword,setKeyword]=useState(''),[type,setType]=useState(''),[selected,setSelected]=useState(''),[historyType,setHistoryType]=useState('전체'),[month,setMonth]=useState('');
  useEffect(()=>{const c=new AbortController();setData(null);setOverview(null);setError('');setLoading(true);setSelected('');setMonth('');setType('');setKeyword('');
    if(from>to){setError('시작월은 종료월보다 늦을 수 없습니다.');setLoading(false);return()=>c.abort();}
    const read=async(path:string)=>{const r=await apiFetch(`${API_BASE_URL}${path}`,{signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();};
    Promise.all([read(`/lake/equipment-evidence?${query}`),read(`/lake/summary?${baseQuery}`)]).then(([d,o])=>{if(c.signal.aborted)return;if(d.snapshot!==o.snapshot)throw new Error('검증본 전환 중 · 새로고침 필요');setData(d);setOverview(o);setSelected(d.installations[0]?.id||'');}).catch(e=>{if(!c.signal.aborted)setError(`장비 근거 조회 실패: ${e.message}`);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();
  },[query,baseQuery,revision]);
  useEffect(()=>{const c=new AbortController();setRefs([]);setRefError('');apiFetch(`${API_BASE_URL}/stations?limit=10000`,{signal:c.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{if(!c.signal.aborted)setRefs(d);}).catch(()=>{if(!c.signal.aborted)setRefError('기존 좌표 기준정보 조회 실패');});return()=>c.abort();},[revision]);
  const installs=data?.installations||[];
  const filtered=installs.filter((r:any)=>(!type||r.device===type)&&`${r.station_name} ${r.device} ${r.serial} ${r.station_codes.join(' ')}`.toLowerCase().includes(keyword.toLowerCase()));
  const current=filtered.find((r:any)=>r.id===selected)||filtered[0];
  const groups=Array.from(new Set<string>(installs.map((r:any)=>r.device||'미확정'))).map(name=>({name,count:installs.filter((r:any)=>(r.device||'미확정')===name).length})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));
  const held=(overview?.stations||[]).filter((s:any)=>!station||station===s.station_code);
  const markers=held.flatMap((s:any)=>{const rr=refs.filter(r=>r.station_id===s.station_code),r=rr.length===1?rr[0]:null;return Number.isFinite(r?.latitude)&&Number.isFinite(r?.longitude)&&Math.abs(r.latitude)<=90&&Math.abs(r.longitude)<=180?[{...s,lat:r.latitude,lng:r.longitude}]:[];});
  const history=[...(data?.maintenance||[]).map((r:any)=>({...r,kind:'정비',date:r.candidate_month})),...(data?.inspections||[]).map((r:any)=>({...r,kind:'점검',date:r.report_date}))].sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id));
  const months=[...new Set<string>(history.map(r=>r.date.slice(0,7)))].sort().reverse();
  const shownMonth=month||months[0]||'';
  const monthly=history.filter(r=>r.date.startsWith(shownMonth));
  const shownHistory=history.filter(r=>(historyType==='전체'||historyType===r.kind)&&(!current||r.linked_station_codes.some((s:string)=>current.linked_station_codes.includes(s))));
  return <div className="p-4 md:p-6 space-y-5 min-h-full bg-gradient-to-br from-blue-50/60 via-white to-indigo-50/40">
    <header className="flex flex-wrap gap-4 justify-between items-end"><div><p className="text-xs text-blue-600 tracking-widest font-bold">EQUIPMENT & OPERATIONS</p><h1 className="text-3xl font-extrabold mt-2">장비 & 운영 관리</h1><p className="text-sm text-slate-500 mt-2">설치·점검·교체 문서와 관측자료를 함께 확인합니다.</p></div><div className="bg-blue-50 border border-blue-100 rounded-xl p-4 text-xs text-blue-800 max-w-sm"><Settings className="w-6 h-6 mb-2"/>문서 기반 운영 검토 지원<br/>AI 장비 고장 예측·교체 시점 추천은 미평가입니다.</div></header>
    <StationClassifications/>
    <div className={`${panel} flex flex-wrap gap-3 items-end text-xs`}><label>자료 출처<DatasetSourceSelect source={source}/></label>
      <label>시작월<input type="month" value={from} onChange={e=>e.target.value&&update({from:e.target.value})} className="block border rounded-lg p-2 mt-1"/></label><label>종료월<input type="month" value={to} onChange={e=>e.target.value&&update({to:e.target.value})} className="block border rounded-lg p-2 mt-1"/></label><label>관측소<select value={station} onChange={e=>update({station:e.target.value})} className="block border rounded-lg p-2 mt-1"><option value="">전체</option>{(overview?.stations||[]).map((s:any)=><option key={s.station_code} value={s.station_code}>{s.station_name||s.station_code}</option>)}</select></label><button onClick={()=>setRevision(n=>n+1)} className="bg-blue-600 text-white px-5 py-2 rounded-lg">새로고침</button></div>
    {loading&&<p role="status" className="text-sm text-blue-600">검증된 문서·관측소 연결을 조회하고 있습니다…</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}
    <p className="text-xs text-slate-500">검증본 {data?.snapshot||'조회 대기'} · {data?.limitations} · 현재 운영 중인 장비의 승인된 등록부와는 별도입니다.</p>
    <div className="grid grid-cols-2 xl:grid-cols-5 gap-4">{[
      ['설치 이력 후보',data?fmt(installs.length):'—','선택 관측소 · 전체 이력',Settings],['점검 문서 행',data?fmt(data.inspections.length):'—','선택 기간 보고서 기준일',CalendarDays],['정비 사건 후보',data?fmt(data.maintenance.length):'—','선택 기간 문서 머리글 월',Wrench],['교체 예정 센서','미확정','승인된 교체 계획 미연결',RefreshCw],['유지보수 완료율','미산정','접수·완료 원장과 분모 필요',ShieldCheck],
    ].map(([t,v,n,Icon]:any)=><section key={t} className={panel}><Icon className="w-6 h-6 text-blue-600 mb-3"/><h2 className="text-xs font-bold">{t}</h2><p className="text-2xl font-extrabold my-2">{v}</p><p className="text-[11px] text-slate-500">{n}</p></section>)}</div>
    <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
      <section className={panel}><h2 className="font-bold mb-3">관측소·장비 근거 지도</h2><div className="h-72 rounded-xl overflow-hidden"><MapContainer center={[36,127.5]} zoom={6} style={{height:'100%',width:'100%'}}><OSMBaseLayer/>{markers.map((s:any)=><CircleMarker key={s.station_code} center={[s.lat,s.lng]} radius={6} pathOptions={{color:'#64748b'}}><Popup><strong>{s.station_name||s.station_code}</strong><p>운영 상태 미확정</p><button className="text-blue-700 underline" onClick={()=>update({station:s.station_code})}>관측소 근거 조회</button></Popup></CircleMarker>)}</MapContainer></div><p className="text-xs text-slate-500 mt-3">{refError||`기존 PostgreSQL 좌표 참조 · 지도 ${markers.length}/${held.length}개소`} · 회색은 미확정</p></section>
      <section className={panel}><h2 className="font-bold mb-3">장비 유형별 설치 이력 후보</h2><p className="text-xs text-slate-500 mb-3">문서의 장비 명칭 기준 · 고유 장비 수 또는 운영 대수가 아닙니다.</p><div className="grid grid-cols-2 gap-3 max-h-72 overflow-auto">{groups.map(g=><button key={g.name} className={`rounded-xl border p-4 text-left ${type===g.name?'border-blue-400 bg-blue-50':'border-blue-100'}`} onClick={()=>setType(type===g.name?'':g.name)}><Settings className="w-5 h-5 text-blue-500 mb-2"/><p className="text-sm font-bold">{g.name}</p><p className="text-xl font-bold mt-2">{fmt(g.count)}<span className="text-xs font-normal ml-1">기록</span></p></button>)}</div>{data&&!groups.length&&<p className="text-sm text-slate-500">연결된 설치 이력 없음 · 장비 없음으로 판정하지 않습니다.</p>}</section>
      <section className={panel}><h2 className="font-bold mb-3">점검·운영 기록 달력</h2><p className="text-xs text-amber-700 mb-3">예정 일정 미연결 · 아래는 수집된 문서의 과거 기록입니다.</p><select aria-label="기록 월" value={shownMonth} onChange={e=>setMonth(e.target.value)} className="border border-blue-100 rounded-lg p-2 text-sm mb-3"><option value="">기록 없음</option>{months.map(m=><option key={m}>{m}</option>)}</select><div className="max-h-56 overflow-auto space-y-3">{monthly.slice(0,30).map(r=><div key={r.kind+r.id} className="text-xs border-b border-slate-100 pb-2"><div className="flex justify-between gap-2"><strong>{r.date} · {r.kind}</strong><span className="text-amber-700">미검토</span></div><p className="text-slate-500 mt-1">{r.station_name||r.linked_station_codes.join(', ')}</p><p className="line-clamp-2 mt-1">{r.excerpt}</p><Citation row={r}/></div>)}</div><p className="text-[10px] text-slate-500 mt-2">{Math.min(30,monthly.length)}/{monthly.length}행 표시 · 날짜 미확정 정비 {fmt(data?.undated_maintenance)} / 점검 {fmt(data?.undated_inspections)} 별도</p></section>
    </div>
    <div className="grid grid-cols-1 xl:grid-cols-4 gap-4">
      <section className={`${panel} xl:col-span-2`}><h2 className="font-bold mb-3">장비·센서 설치 근거 목록</h2><div className="flex flex-wrap gap-2 mb-3 text-xs"><input aria-label="장비·관측소·일련번호 검색" placeholder="장비·관측소·일련번호 검색" value={keyword} onChange={e=>setKeyword(e.target.value)} className="border rounded-lg p-2 flex-1"/><select aria-label="장비 유형" value={type} onChange={e=>setType(e.target.value)} className="border rounded-lg p-2"><option value="">전체 장비 유형</option>{groups.map(g=><option key={g.name}>{g.name}</option>)}</select></div><p className="text-[11px] text-slate-500 mb-3">{data?.installation_scope}</p><div className="max-h-96 overflow-auto"><table className="w-full text-xs text-left"><thead className="bg-blue-50 sticky top-0"><tr>{['관측소','장비 / 일련번호 후보','설치 날짜 원문','유효기간','검토'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map((r:any)=><tr key={r.id} className={`border-b border-slate-100 ${current?.id===r.id?'bg-blue-50':''}`}><td className="p-2">{r.station_name}<span className="block text-[10px] text-slate-500">{r.linked_station_codes.join(', ')}</span></td><td className="p-2">{r.device||'미확정'}<span className="block text-slate-500">{r.serial||'미확정'}</span></td><td className="p-2">{r.date_raw||'미확정'}<span className="block text-[10px] text-slate-500">정밀도 {r.date_precision||'미확정'}</span></td><td className="p-2">{r.valid_from||'미확정'} ~ {r.valid_to||'미확정'}</td><td className="p-2"><button className="border border-blue-200 rounded px-2 py-1 text-blue-700" aria-pressed={current?.id===r.id} onClick={()=>setSelected(r.id)}>상세</button></td></tr>)}</tbody></table></div><p className="text-xs text-slate-500 mt-3">검색 결과 {filtered.length}/{installs.length}기록 · 중복 문서와 복수 설치 주장이 포함될 수 있습니다.</p></section>
      <section className={panel}><h2 className="font-bold mb-4">장비 생애주기 · 근거 검토</h2>{current?<><h3 className="text-sm font-bold mb-4">{current.station_name} · {current.device}</h3><ol className="border-l-2 border-blue-200 ml-2 pl-4 space-y-5 text-xs">{[['설치 주장',current.date_raw||'미확정'],['물리 센서 식별',`일련번호 후보 ${current.serial||'미확정'} · 미승인`],['사용 시작·종료',`${current.valid_from||'미확정'} ~ ${current.valid_to||'미확정'}`],['다음 점검·교체 일정','승인 계획 미연결']].map(([a,b])=><li key={a}><p className="font-bold text-blue-900">{a}</p><p className="text-slate-500 mt-1">{b}</p></li>)}</ol><Citation row={current}/><p className="text-xs text-amber-700 mt-4">문서의 설치 날짜와 실제 센서 사용기간은 동일하다고 가정하지 않습니다.</p>{(data?.conflicts||[]).filter((c:any)=>current.linked_station_codes.includes(c.station_code)).map((c:any)=><p key={c.id} className="text-xs bg-red-50 text-red-800 p-3 rounded-lg mt-3">충돌: {c.reason}</p>)}<div className="space-y-2 mt-4">{current.linked_station_codes.map((s:string)=><Link key={s} to={`/profile/${encodeURIComponent(s)}?${linkQuery}`} className="block text-xs text-blue-700 underline">{s} 관측기간·항목 근거 →</Link>)}</div></>:<p className="text-sm text-slate-500">선택 범위에 설치 이력 후보가 없습니다.</p>}</section>
      <section className={panel}><h2 className="font-bold mb-3">관측소 운영 이력 후보</h2><p className="text-[11px] text-slate-500 mb-3">{current?current.station_name:'선택 범위 전체'} · 선택 장비 일련번호까지 연결된 이력은 아닙니다.</p><div className="flex gap-2 text-xs mb-3">{['전체','정비','점검'].map(t=><button key={t} aria-pressed={historyType===t} onClick={()=>setHistoryType(t)} className={`p-2 rounded-lg ${historyType===t?'bg-blue-600 text-white':'bg-blue-50 text-blue-700'}`}>{t}</button>)}</div><div className="max-h-96 overflow-auto space-y-4">{shownHistory.slice(0,40).map(r=><article key={r.kind+r.id} className="border-b border-slate-100 pb-3 text-xs"><p className="font-bold text-blue-900">{r.date} · {r.kind} 기록</p><p className="whitespace-pre-wrap mt-2">{r.excerpt}</p><Citation row={r}/></article>)}</div><p className="text-[10px] text-slate-500 mt-3">{Math.min(40,shownHistory.length)}/{shownHistory.length}행 · 정비는 문서 머리글 월, 점검은 보고일 기준입니다. 사건 발생 시각과 다를 수 있습니다.</p></section>
    </div>
  </div>;
}
