import {Fragment,useEffect,useMemo,useRef,useState} from 'react';
import {X,RefreshCw,ShieldCheck,TriangleAlert,BrainCircuit,Database,Clock,ChevronLeft,ChevronRight} from 'lucide-react';
import {API_BASE_URL,apiFetch} from '../api/client';
import {observationItemLabel} from '../data/observationAvailability';
import {qcDetailQuery,validQCCandidateDetail,qcDetailPlot,qcDetailActionAvailability,qcNumber,qcValueNumber,qcLiteralLabel,qcPage,qcStateLabel,type QCDailyOverview,type QCDailyRequest,type QCCandidateDetail,type QCDetailPoint,type QCCapability} from '../data/qcWorkspace';
import {QCPanelHeading} from './QCWorkspaceCharts';

const stateText=(state:string)=>({AVAILABLE:'확인된 저장 결과',NOT_EXECUTED:'AI 분석 미실행',NO_MODEL:'사용 가능한 모델 없음',UNVERIFIED:'판본·시각 근거 확인 필요',NO_EVIDENCE:'관련 Evidence 없음',NO_LINKED_EVIDENCE:'연결된 Evidence 없음',APPROVED_SOURCE_EPISODE_ONLY:'승인 원천의 센서 유효기간',NO_LINKED_WORKFLOW:'연결된 승인 Workflow 없음',COMPLETED:'검토 처리 완료',PENDING:'담당자 검토 대기',APPROVED:'검토 결정 승인 · 재개 대기',REJECTED:'검토 반려',CANCELLED:'검토 취소',PARTIAL:'일부 근거만 확인'} as Record<string,string>)[state]||state;
const errorText=async(response:Response)=>{let data:any;try{data=await response.json();}catch{data=null;}return (typeof data?.detail==='string'?data.detail:data?.detail?.code||data?.code||'요청 실패')+' (HTTP '+response.status+')';};

function DetailSeries({detail,catalog}:{detail:QCCandidateDetail;catalog:QCDailyOverview['flag_catalog']}){
 const [span,setSpan]=useState(120),[point,setPoint]=useState<QCDetailPoint|null>(null),[showAI,setShowAI]=useState(true),[page,setPage]=useState(1);
 const plot=useMemo(()=>qcDetailPlot(detail,span),[detail,span]),rowPage=qcPage(plot.points,page,50),selected=point||detail.observation;
 const flag=(code:string|null)=>catalog.find(f=>f.code===(code||'UNKNOWN')),prediction=plot.predictions,unit=detail.observation.unit||'원천값';
 const clockLabel=(n:number)=>plot.points.find(p=>Math.abs(p.time-n)<1000)?.row.observation_time.slice(11,19)||'';
 return <section className="qc-panel" id="qc-detail-series"><QCPanelHeading title="실제 관측 시계열" note="기본 발생 전후 ±2시간입니다. 조회 기준 이후 자료는 제외하며 결측·빈값을 보간하지 않습니다."><span className="qc-pill">{detail.surrounding_timeseries.truncated?'일부 행만 조회':qcNumber(detail.surrounding_timeseries.rows.length)+'행'}</span></QCPanelHeading>
 <div className="qc-drawer-chart-controls"><label>시간 확대<select aria-label="QC 상세 시계열 확대" value={span} onChange={e=>{setSpan(Number(e.target.value));setPage(1);setPoint(null);}}><option value="120">전후 2시간</option><option value="60">전후 1시간</option><option value="30">전후 30분</option><option value="10">전후 10분</option></select></label><button className="qc-link-button" disabled={span<=10} onClick={()=>{setSpan(old=>old>60?60:old>30?30:10);setPage(1);}}>확대 +</button><button className="qc-link-button" disabled={span>=120} onClick={()=>{setSpan(old=>old<30?30:old<60?60:120);setPage(1);}}>축소 −</button>{detail.ai.status==='AVAILABLE'&&<label><input type="checkbox" checked={showAI} onChange={e=>setShowAI(e.target.checked)}/>저장된 AI 기대값</label>}<span>{unit} · {plot.discrete?'방향 원문은 개별 점으로 표시':'실제 시각 간격'}</span></div>
 <div className="qc-drawer-chart"><svg viewBox="0 0 912 280" role="img" aria-label="실제 관측값, Rule 플래그, 지연 이력과 자료 격자 공백의 시계열"><title>원자료 시계열 · 자동 보간 없음</title>{[0,.25,.5,.75,1].map(r=><g key={r}><line x1="52" x2="876" y1={26+r*212} y2={26+r*212} stroke="#e6eef8" strokeDasharray="3 4"/><text x="45" y={30+r*212} textAnchor="end">{qcValueNumber(plot.max-r*(plot.max-plot.min))}</text></g>)}{plot.gaps.map((g,i)=><rect key={g.observation_time+'-'+i} className="gap" x={g.x-2} y="26" width="4" height="212"><title>{g.observation_time} · 관측 시각 격자의 추정 공백 · 수신 결측 확정 아님</title></rect>)}<line className="issue" x1={plot.issueX} x2={plot.issueX} y1="22" y2="242"/><text x={Math.max(65,Math.min(820,plot.issueX+5))} y="17">선택 발생 시각</text>{plot.segments.filter(s=>s.length>1).map((segment,i)=><polyline key={i} className="actual" points={segment.map(p=>`${p.x},${p.y}`).join(' ')}/>)}{plot.points.map(p=>p.y!==null?<g key={p.index}><circle cx={p.markerX} cy={p.y} r={flag(p.row.flag)?.semantic==='GOOD'?2.3:3.5} fill={flag(p.row.flag)?.color||'#1684ff'} stroke="white" strokeWidth=".5" onMouseEnter={()=>setPoint(p.row)}><title>{p.row.observation_time} · 실제값 {qcValueNumber(p.row.value)} · {flag(p.row.flag)?.label||'QC 미평가'}{p.duplicates>1?' · 동일 시각 원문 '+p.duplicates+'행':''}</title></circle>{p.row.late_history.length>0&&<path className="late" d={`M ${p.markerX} ${p.y-10} l -4 -7 h 8 Z`}><title>수신 지연 이력 · {p.row.delay_minutes}분 · {p.row.received_time}</title></path>}</g>:<text key={p.index} x={p.markerX} y="235" textAnchor="middle">×<title>{p.row.observation_time} · 원천 수치 없음 · {qcLiteralLabel(p.row.value_raw)}</title></text>)}{showAI&&prediction.map((r,i)=><g key={String(r.id)+i}><circle cx={r.x+6*i} cy={r.y} r="5" fill="white" stroke="#a17aeb" strokeWidth="2"><title>저장된 {r.model} {r.model_version} 기대값 {qcValueNumber(r.predicted_value)} · Residual {qcValueNumber(r.residual)}</title></circle>{detail.observation.value!==null&&<line className="prediction" x1={r.x+6*i} x2={r.x+6*i} y1={r.y} y2={plot.y(detail.observation.value)}/>}</g>)}<line x1="52" x2="876" y1="242" y2="242" stroke="#cedeed"/><text x="52" y="261">{clockLabel(plot.points[0]?.time||plot.start)}</text><text x="464" y="261" textAnchor="middle">{detail.observation.observation_time.slice(11,19)}</text><text x="876" y="261" textAnchor="end">{clockLabel(plot.points[plot.points.length-1]?.time||plot.end)}</text><text x="464" y="275" textAnchor="middle">{qcStateLabel(detail.window.clock_basis)}</text></svg></div>
 <div className="qc-chart-legend">{catalog.map(f=><span key={f.code}><i style={{background:f.color}}/>{f.label} ({f.code})</span>)}<span><i style={{background:'#f0a028'}}/>수신 지연 이력</span><span><i style={{background:'#dce6f0'}}/>관측 격자 추정 공백</span>{prediction.length>0&&<span><i style={{background:'#a17aeb'}}/>저장된 AI 기대값 · 선 보간 없음</span>}</div>
 <div className="qc-drawer-record"><strong>{selected.observation_time}</strong><p>실제값 {qcLiteralLabel(selected.value_raw)} · 수치 {qcValueNumber(selected.value)} {unit} · Rule {flag(selected.flag)?.label||'미실행'}</p><p>수신시각 {selected.received_time||'확인된 수신시각 없음'} · 지연 {selected.delay_minutes===null?'미산정':qcNumber(selected.delay_minutes)+'분'} · 지연 Flag {flag(selected.delay_flag)?.label||qcStateLabel(selected.delay_flag)}</p></div>
 <p className="qc-panel-note">{detail.surrounding_timeseries.window_start} ~ {detail.surrounding_timeseries.window_end} · {detail.surrounding_timeseries.cadence_status==='INFERRED_FROM_OBSERVED_CLOCKS'?'관측시각에서 추정한 주기 '+qcNumber(detail.surrounding_timeseries.cadence_seconds)+'초':'관측주기 근거 미확정'} · 공백은 예정 관측·수신 결측을 확정하지 않습니다.{detail.surrounding_timeseries.truncated?' 상세 자료가 일부만 조회되었습니다.':''}</p>
 {detail.ai.status!=='AVAILABLE'&&<p className="qc-detail-state"><BrainCircuit size={14}/> {stateText(detail.ai.status)} · 저장된 예측값 없음</p>}
 <details><summary className="qc-link-button">실제 원문·관측·수신시각 표 보기</summary><div className="qc-drawer-rows"><table><thead><tr><th>관측시각</th><th>실제값</th><th>Rule Flag</th><th>수신시각</th><th>지연(분)</th><th>원문 QC</th></tr></thead><tbody>{rowPage.rows.map(p=><tr key={p.index}><td><button className="qc-link-button" aria-label={p.row.observation_time+' 원문 행 보기'} onClick={()=>setPoint(p.row)}>{p.row.observation_time}</button></td><td>{qcLiteralLabel(p.row.value_raw)}</td><td>{flag(p.row.flag)?.label||'미실행'}</td><td>{p.row.received_time||'미확인'}</td><td>{qcNumber(p.row.delay_minutes)}</td><td className="qc-raw-literal">{qcLiteralLabel(p.row.qc_source_literals||{QC:p.row.source_qc_raw,MQ:p.row.source_mqc_raw})}</td></tr>)}</tbody></table></div><div className="qc-table-pagination"><span>{rowPage.first} - {rowPage.last} / {plot.points.length}행</span><nav aria-label="상세 원문 시계열 페이지"><button disabled={rowPage.page<=1} aria-label="이전 상세 시계열" onClick={()=>setPage(rowPage.page-1)}><ChevronLeft size={12}/></button><span>{rowPage.page}/{rowPage.pages}</span><button disabled={rowPage.page>=rowPage.pages} aria-label="다음 상세 시계열" onClick={()=>setPage(rowPage.page+1)}><ChevronRight size={12}/></button></nav></div></details>
 </section>;
}

export default function QCCandidateDrawer({id,overview,request,onClose,onChanged}:{id:string;overview:QCDailyOverview;request:QCDailyRequest;onClose:()=>void;onChanged:()=>void}){
 const [frame,setFrame]=useState<{key:string;packet:QCCandidateDetail}|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[actor,setActor]=useState<{user_id:string;role:string}|null>(null),[sessionText,setSessionText]=useState('실제 담당 계정은 운영 단계에서 설정합니다.'),[checking,setChecking]=useState(false),[comment,setComment]=useState(''),[busy,setBusy]=useState(''),[actionMessage,setActionMessage]=useState('');
 const drawer=useRef<HTMLDivElement>(null),query=qcDetailQuery(overview,request),key=JSON.stringify([id,query,overview.result_sha256,revision]),packet=frame?.key===key?frame.packet:null;
 useEffect(()=>{const controller=new AbortController();setFrame(null);setError('');apiFetch(API_BASE_URL+'/qc/candidates/'+encodeURIComponent(id)+'?'+query,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(await errorText(response));return response.json();}).then(data=>{if(controller.signal.aborted)return;if(!validQCCandidateDetail(data,id,overview,request))throw new Error('상세 원천·시간창·관측소·센서·Rule·저장 AI 근거가 조회 조건과 일치하지 않습니다.');setFrame({key,packet:data});}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[id,key,query,overview,request]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';drawer.current?.focus();return()=>{document.body.style.overflow=overflow;previous?.focus();};},[]);
 const keyDown=(e:React.KeyboardEvent)=>{if(e.key==='Escape'&&!busy){e.preventDefault();onClose();}if(e.key==='Tab'){const nodes=Array.from(drawer.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),summary')||[]);if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};
 const checkActor=async()=>{setChecking(true);try{const response=await apiFetch(API_BASE_URL+'/session');if(!response.ok){setActor(null);setSessionText(response.status===503?'승인 계정 미설정 · 근거 조회는 가능합니다.':await errorText(response));return;}const user=await response.json();if(typeof user.user_id!=='string'||!user.user_id||!['operator','reviewer','admin'].includes(user.role))throw new Error('담당자 응답 확인 실패');setActor(user);setSessionText(user.user_id+' · '+user.role);setRevision(old=>old+1);}catch(e){setActor(null);setSessionText(e instanceof Error?e.message:'담당자 확인 실패');}finally{setChecking(false);}};
 const action=async(c:QCCapability)=>{const gate=qcDetailActionAvailability(packet,c,actor);if(!gate.enabled||!packet||busy)return;if(!comment.trim()){setActionMessage('담당 검토 의견을 입력하세요.');return;}setBusy(c.action);setActionMessage('');try{const body={...c.body_template,request_key:crypto.randomUUID(),comment:comment.trim()};const response=await apiFetch(API_BASE_URL+c.endpoint.replace(/^\/api/,''),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){const reason=await errorText(response);if([401,403,409].includes(response.status)){setFrame(null);setRevision(old=>old+1);if(response.status!==409)setActor(null);}throw new Error(reason);}const result=await response.json();if(result.workflow_id!==packet.workflow.workflow_id||typeof result.status!=='string'||result.revision!==packet.workflow.revision+1)throw new Error('처리 응답의 대상·revision 확인 실패. 최신 이력을 다시 조회하세요.');setActionMessage('처리됨 · '+stateText(result.status)+' · 원천값·Final QC 수정 없음');setRevision(old=>old+1);onChanged();}catch(e){setActionMessage(e instanceof Error?e.message:'검토 처리 실패');}finally{setBusy('');}};
 const obs=packet?.observation,item=obs?.variable_code||obs?.item_code||'',station=obs?.station_id||obs?.station_code||'',flags=overview.flag_catalog,flag=(code:string|null|undefined)=>flags.find(f=>f.code===(code||'UNKNOWN'));
 return <div className="qc-drawer-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><div className="qc-candidate-drawer" ref={drawer} role="dialog" aria-modal="true" aria-labelledby="qc-detail-title" tabIndex={-1} onKeyDown={keyDown}><header className="qc-drawer-heading"><div><h2 id="qc-detail-title">{id.startsWith('archive:')?'보존 원문 상세':'QC 상세검토'}</h2><p>{station} {observationItemLabel(item)} · {overview.window.start} ~ {overview.window.end}<br/>조회 기준 {overview.window.as_of} · {id.startsWith('archive:')?'미해석 원문 · 승인 후보와 별도':'저장된 Rule QC 후보'}</p></div><button aria-label="QC 상세검토 닫기" disabled={Boolean(busy)} onClick={onClose}><X size={18}/></button></header><div className="qc-drawer-body">{error?<div role="alert" className="qc-error-banner"><TriangleAlert size={16}/><span>{error}</span><button className="qc-primary-button" onClick={()=>setRevision(v=>v+1)}>상세 다시 조회</button></div>:!packet?<p role="status" className="qc-loading">같은 시간창·원천 권위의 실제 상세를 조회하고 있습니다…</p>:<><nav className="qc-drawer-tabs" aria-label="QC 상세검토 구역"><a href="#qc-detail-series">시계열</a><a href="#qc-detail-rule">Rule</a><a href="#qc-detail-ai">AI</a><a href="#qc-detail-equipment">장비</a><a href="#qc-detail-evidence">Evidence</a><a href="#qc-detail-actions">담당자 처리</a></nav>
 <dl className="qc-drawer-observation"><div><dt>발생시각</dt><dd>{obs!.observation_time}</dd></div><div><dt>실제 관측값</dt><dd>{qcValueNumber(obs!.value)} <small>{obs!.unit||'원천값 · 단위 미확정'}</small></dd></div><div><dt>1차 Rule Flag</dt><dd style={{color:flag(obs!.flag)?.color}}>{flag(obs!.flag)?.label||'미평가'} <small>{obs!.flag||'원문 QC 의미 미해석'}</small></dd></div><div><dt>DB 수신 / 지연</dt><dd>{obs!.received_time||'수신시각 근거 없음'}<br/><small>{obs!.delay_minutes===null?'지연 미산정':qcNumber(obs!.delay_minutes)+'분 · 이력 보존'}</small></dd></div></dl>
 <DetailSeries key={packet.result_sha256} detail={packet} catalog={flags}/>
 <section className="qc-panel" id="qc-detail-rule"><QCPanelHeading title="Rule QC 상세" note="실제로 저장된 평가와 그때 사용한 Threshold·판본입니다."/>{packet.rule_results.rows.length?<div className="qc-drawer-rows"><table className="qc-drawer-rule-table"><thead><tr><th>Rule</th><th>Threshold / 구성</th><th>실제 입력값</th><th>Rule Version</th><th>Flag</th><th>평가 사유</th></tr></thead><tbody>{packet.rule_results.rows.map(r=><tr key={r.id}><td>{r.rule_name}<br/>{r.rule_type}</td><td>{qcLiteralLabel(r.threshold_value)}<details><summary>실제 구성</summary><pre>{JSON.stringify(r.threshold_definition,null,2)}</pre></details></td><td>{qcValueNumber(r.input_value)}</td><td>{r.rule_version}</td><td style={{color:flag(r.flag)?.color}}>{flag(r.flag)?.label} ({r.flag})</td><td>{r.reason||r.evaluation_status}</td></tr>)}</tbody></table></div>:<p className="qc-detail-state">1차 Rule QC 미실행 · {packet.rule_results.reason||'선택 행에 연결된 검증 결과 없음'}</p>}</section>
 <div className="qc-drawer-grid"><section className="qc-panel" id="qc-detail-ai"><QCPanelHeading title="AI 분석" note="이 화면은 저장된 결과만 읽습니다. 클릭으로 추론·학습을 실행하지 않습니다."/>{packet.ai.status==='AVAILABLE'?packet.ai.results.map(r=><div key={r.id}><h3>{r.model} · {r.model_version}</h3><dl>{[['정상 기대값',r.predicted_value],['Residual',r.residual],['Anomaly Score',r.anomaly_score],['Confidence',r.confidence],['Drift Score',r.drift_score],['Level Shift',r.level_shift]].map(([name,value])=><Fragment key={String(name)}><dt>{name}</dt><dd>{qcValueNumber(value)}</dd></Fragment>)}</dl><p className="qc-panel-note">저장된 기대값 · 실제값에서 계산한 Residual · 활성 Serving 상태는 별도 확인 필요</p><details><summary className="qc-link-button">모델 SHA·가용시각</summary><pre>{JSON.stringify(r,null,2)}</pre></details></div>):<p className="qc-detail-state"><BrainCircuit size={15}/> {stateText(packet.ai.status)}<br/>{packet.ai.reason||'확인된 Prediction·Residual·Score 없음'}</p>}</section>
 <section className="qc-panel" id="qc-detail-equipment"><QCPanelHeading title="장비·센서 유효기간"/>{['APPROVED_SOURCE_EPISODE_ONLY','EXPLICIT_LINKED_EQUIPMENT_EVENTS'].includes(packet.equipment_epoch.status)?<><dl>{[['Sensor ID',packet.equipment_epoch.sensor_id],['물리 센서',packet.equipment_epoch.physical_sensor_id],['Equipment Epoch',packet.equipment_epoch.sensor_episode_id],['유효 시작',packet.equipment_epoch.effective_start],['유효 종료',packet.equipment_epoch.effective_end],['설치일',packet.equipment_epoch.install_date],['교체일',packet.equipment_epoch.replacement_date],['검교정일',packet.equipment_epoch.calibration_date]].map(([name,value])=><Fragment key={String(name)}><dt>{name}</dt><dd>{value||'확인된 이력 없음'}</dd></Fragment>)}</dl>{packet.equipment_epoch.status==='EXPLICIT_LINKED_EQUIPMENT_EVENTS'&&<><p className="qc-panel-note">설치·교체·검교정 근거가 이 관측행과 연결되었습니다. 장비 이력의 담당 승인과 별도입니다.</p><details><summary className="qc-link-button">장비 이력의 실제 근거 보기</summary><pre>{JSON.stringify(packet.equipment_epoch.events,null,2)}</pre></details></>}</>:<p className="qc-detail-state">센서·장비 유효기간 근거 없음<br/>현재 메타데이터를 과거 설치·교체·검교정 이력으로 사용하지 않습니다.</p>}</section></div>
 <section className="qc-panel qc-drawer-evidence" id="qc-detail-evidence"><QCPanelHeading title="관련 Evidence" note="같은 관측행·항목·센서·조회 기준에 연결된 운영·점검·문서만 표시합니다."/>{[['operations','운영이력'],['inspection','점검·정비'],['rag','관련 가이드북·유사 과거사례·RAG 문서']].map(([name,label])=><div key={name}><h3>{label}</h3>{packet.evidence[name].rows.length?packet.evidence[name].rows.map((row:any,i:number)=><details key={row.id||row.chunk_id||i}><summary>{row.title||row.event_type||'근거 '+(i+1)} · {row.event_time||row.available_at}</summary><p>{row.text||row.action_taken}</p><pre>{JSON.stringify(row,null,2)}</pre></details>):<p className="qc-detail-state">{stateText(packet.evidence[name].status)}{packet.evidence[name].reason?' · '+packet.evidence[name].reason:''}</p>}</div>)}</section>
 <section className="qc-panel qc-drawer-actions" id="qc-detail-actions"><QCPanelHeading title="담당자 처리·Review history" note="현재 승인 Workflow의 실제 대상·권한·revision·추천 hash를 확인합니다. 원천값·Final QC는 이 단계에서 자동 수정하지 않습니다."><span className="qc-pill">{stateText(packet.workflow.status)}</span></QCPanelHeading>{Object.values(packet.workflow.excluded_counts||{}).some(n=>typeof n==='number'&&n>0)&&<p className="qc-detail-state">일부 검토 작업의 시각·판본 근거를 확인하지 못했습니다. 연결 없음과 근거 미확정을 구분하여 확인하세요.</p>}<div className="qc-actor"><span>{sessionText}</span><button disabled={checking||Boolean(busy)} onClick={checkActor}><RefreshCw size={12}/>{checking?'확인 중':'담당자·권한 확인'}</button></div><label>담당자 검토 의견<textarea aria-label="QC 상세 검토 의견" value={comment} maxLength={4000} onChange={e=>setComment(e.target.value)} placeholder="관측값과 근거를 확인한 의견을 입력하세요."/></label><div className="qc-drawer-action-buttons">{packet.capabilities.length?packet.capabilities.map(c=>{const gate=qcDetailActionAvailability(packet,c,actor),label=({APPROVED:'검토 결정 승인',REJECTED:'검토 반려',RESUME:'승인 작업 재개',CANCEL:'작업 취소'} as Record<string,string>)[c.action]||c.action;return <button key={c.action} disabled={!gate.enabled||Boolean(busy)} title={gate.reason} onClick={()=>action(c)}>{busy===c.action?'처리 중…':label}</button>;}):<><button disabled title="선택 행에 연결된 승인 Workflow 없음">검토 승인</button><button disabled title="선택 행에 연결된 승인 Workflow 없음">보류</button><button disabled title="선택 행에 연결된 승인 Workflow 없음">반려</button></>}{flags.filter(f=>['GOOD','SUSPECT','BAD','MISSING'].includes(f.semantic)).map(f=><button key={f.code} disabled title="이 후보에 연결된 Final QC 승인 대상·판본 검증이 없어 수정할 수 없습니다." style={{color:f.color}}>{f.label}로 플래그 수정</button>)}</div><p className="qc-panel-note">{packet.capabilities.length?packet.capabilities.map(c=>qcDetailActionAvailability(packet,c,actor).reason).filter(Boolean).filter((v,i,all)=>all.indexOf(v)===i).join(' · '):packet.kind==='ARCHIVE_RAW_SAMPLE'?'보존 원문은 승인 대상과 별도입니다. 실제 담당 계정은 운영 단계에서 설정합니다.':'이 관측행에 연결된 승인 Workflow·담당 권한이 없습니다.'}</p>{actionMessage&&<p role="status" className="qc-detail-state">{actionMessage}</p>}{packet.review_history.length?packet.review_history.map((row,i)=><div className="qc-drawer-history" key={row.revision||i}>{row.created_at} · {row.actor_id||'담당자'} · {row.action} · {row.from_status} → {row.to_status}<details><summary>처리 근거·revision</summary><pre>{JSON.stringify(row,null,2)}</pre></details></div>):<p className="qc-detail-state">확인된 Review history 없음</p>}</section>
 <details className="qc-panel qc-provenance"><summary><ShieldCheck size={14}/>원천·시각·계약·SHA 근거</summary><p><Clock size={12}/> {packet.window.clock_basis} · {packet.window.as_of}</p><p><Database size={12}/> {packet.source} · {packet.snapshot||'승인 원장'}</p><pre>{JSON.stringify({observation:packet.observation,scope:packet.scope,provenance:packet.provenance,window_id:packet.window.window_id,result_sha256:packet.result_sha256},null,2)}</pre></details></> }</div></div></div>;
}
