import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {BrainCircuit,ChevronLeft,ChevronRight,Search,ShieldCheck,TriangleAlert,ArrowRight,RefreshCw,CheckCircle2} from 'lucide-react';
import {API_BASE_URL,apiFetch} from '../api/client';
import {observationItemLabel} from '../data/observationAvailability';
import {matchesLakeSeries} from '../data/observationCutoff';
import {qcNumber,qcValueNumber,qcLiteralLabel,qcReasonText,qcCaseRows,qcPage,qcActionAvailability,qcStateLabel,type QCCase,type QCScope,type QCWorkspacePacket,type QCDailyOverview} from '../data/qcWorkspace';
import ObservationSeriesChart from './ObservationSeriesChart';
import {QCPanelHeading} from './QCWorkspaceCharts';

export function QCCaseTable({packet,selected,onSelect,search,onSearch,sort,onSort}:{packet:QCWorkspacePacket|null;selected?:QCCase;onSelect:(key:string)=>void;search:string;onSearch:(query:string)=>void;sort:string;onSort:(order:string)=>void}){
  const [requestedPage,setRequestedPage]=useState(1);
  const rows=useMemo(()=>qcCaseRows(packet?.cases.rows||[],search,sort,Object.fromEntries((packet?.filters.stations||[]).map(row=>[row.station_code,row.station_name]))),[packet,search,sort]);
  const page=qcPage(rows,requestedPage,6),name=(code:string)=>packet?.filters.stations.find(row=>row.station_code===code)?.station_name||code;
  useEffect(()=>{setRequestedPage(1);},[packet?.result_sha256,search,sort]);
  return <section className="qc-panel qc-cases" aria-label="주요 품질 검토 사례"><QCPanelHeading title="주요 품질 검토 사례" note="이상 탐지 결과가 아니라 기준시각 이전의 최신 원문 표본입니다."><span className="qc-pill">최신 원문 {packet?.cases.rows.length??'—'}행</span></QCPanelHeading>
    <div className="qc-case-tools"><label><Search size={13}/><input aria-label="품질 사례 검색" value={search} onChange={event=>onSearch(event.target.value)} placeholder="관측소·항목·원문 코드 검색"/></label><select aria-label="품질 사례 정렬" value={sort} onChange={event=>onSort(event.target.value)}><option value="clock_desc">최근 시각순</option><option value="clock_asc">이전 시각순</option><option value="station">관측소순</option></select></div>
    <div className="qc-case-scroll"><table><thead><tr><th>관측소</th><th>항목</th><th>관측시각</th><th>원천값</th><th>원문 QC</th><th>검토 상태</th></tr></thead><tbody>{page.rows.map(row=><tr key={row.case_key} className={selected?.case_key===row.case_key?'selected':''}><td><button aria-pressed={selected?.case_key===row.case_key} aria-label={name(row.station_code)+' '+observationItemLabel(row.item_code)+' '+row.observed_time_raw+' 사례 선택'} title={row.station_code} onClick={()=>onSelect(row.case_key)}>{name(row.station_code)}</button></td><td title={row.item_code}>{observationItemLabel(row.item_code)}</td><td title={row.observed_time_raw}>{row.observed_time_raw.slice(5,16)}</td><td title={row.value_raw===null?'NULL':String(row.value_raw)}>{row.value_raw===null?'NULL':row.value_raw===''?'빈 문자열':String(row.value_raw)}</td><td className="qc-raw-literal">{qcLiteralLabel(row.source_qc_raw)}</td><td><span className="qc-state unknown">의미 미해석</span></td></tr>)}{!rows.length&&<tr><td colSpan={6} className="qc-empty">{packet?'선택 조건의 최신 원문 표본 없음':'원문 사례 조회 중'}</td></tr>}</tbody></table></div>
    <div className="qc-table-pagination"><span>{page.first} - {page.last} / {rows.length}개 표본</span><nav aria-label="품질 사례 페이지"><button aria-label="이전 품질 사례 페이지" disabled={page.page<=1} onClick={()=>setRequestedPage(page.page-1)}><ChevronLeft size={13}/></button><span>{page.page} / {page.pages}</span><button aria-label="다음 품질 사례 페이지" disabled={page.page>=page.pages} onClick={()=>setRequestedPage(page.page+1)}><ChevronRight size={13}/></button></nav></div>
    <p className="qc-panel-note">전체 대응 원문 {qcNumber(packet?.cases.total_matching_rows)}행 중 최근 {packet?.cases.limit??'—'}행 이내를 표시합니다. 미해석은 정상·이상 판정이 아닙니다.</p>
  </section>;
}

export function QCReviewPanel({packet,selected,linkQuery}:{packet:QCWorkspacePacket|null;selected?:QCCase;linkQuery:string}){
  const [actor,setActor]=useState<{user_id:string;role:string}|null>(null),[sessionState,setSessionState]=useState('승인 계정은 실제 운영 단계에서 설정합니다.'),[checking,setChecking]=useState(false);
  const checkActor=async()=>{setChecking(true);try{const response=await apiFetch(API_BASE_URL+'/session');if(!response.ok){setActor(null);setSessionState(response.status===503?'승인 계정 미설정 · 조회·검토 근거 확인은 가능합니다.':'담당자 연결·권한을 확인하세요.');return;}const data=await response.json();if(typeof data.user_id!=='string'||!data.user_id||!['operator','reviewer','admin'].includes(data.role))throw new Error('담당자 응답 확인 실패');setActor(data);setSessionState(data.user_id+' · '+data.role);}catch{setActor(null);setSessionState('담당자 연결을 확인하지 못했습니다. 다시 확인할 수 있습니다.');}finally{setChecking(false);}};
  const actions=[['hold','검토 보류'],['flag_change','플래그 수정'],['approve','승인 처리']] as const;
  return <section className="qc-panel qc-review" aria-label="AI 기반 품질 검토 지원"><QCPanelHeading title="AI 기반 품질 검토 지원" note="원문 문자열을 AI 추천이나 승인 플래그로 바꾸지 않습니다."><a href="#qc-workflow-tools" className="qc-link-button">검토 작업 조회<ChevronRight size={12}/></a></QCPanelHeading>
    <div className="qc-ai-result"><span className="qc-ai-result-icon"><TriangleAlert size={24}/></span><div><small>AI 추천 플래그</small><strong>미평가</strong><span>확인된 추천 결과 없음</span></div><div className="qc-ai-confidence"><small>신뢰도</small><strong>—</strong><span className="qc-confidence-track"/></div></div>
    <h3>주요 판단 근거</h3><ul className="qc-review-evidence"><li>기준시각 {packet?.cutoff_native||'조회 중'} · 원문 QC 의미·판본 확인 필요</li><li>동일 범위의 AI 예측 {qcNumber(packet?.review.ai_prediction_count)}건 · Label {qcNumber(packet?.review.ai_label_count)}건</li><li>기준시각의 검토 workflow {qcNumber(packet?.review.workflow_count)}건 · 승인 {qcNumber(packet?.review.approved_count)}건</li></ul>
    {selected?<div className="qc-selected-raw"><strong>{packet?.filters.stations.find(row=>row.station_code===selected.station_code)?.station_name||selected.station_code} · {observationItemLabel(selected.item_code)}</strong><p>{selected.observed_time_raw} · 원천값 {selected.value_raw===null?'NULL':String(selected.value_raw)}</p><p className="qc-raw-literal">원문 QC {qcLiteralLabel(selected.source_qc_raw)} · MQ {qcLiteralLabel(selected.source_mq_raw)}</p><Link to={'/profile/'+encodeURIComponent(selected.station_code)+'?'+linkQuery+'&item='+encodeURIComponent(selected.item_code)}>실제 관측값·시계열 보기<ArrowRight size={12}/></Link></div>:<div className="qc-review-prompt"><BrainCircuit size={19}/><p>사례를 선택해 원천 행과 실제 시계열을 확인하세요.</p></div>}
    <details className="qc-review-reasons"><summary>미평가 사유·승인 준비 근거</summary><ul>{(packet?.review.reasons||[]).map(reason=><li key={reason} title={reason}>{qcReasonText(reason)}</li>)}</ul><p>{packet?.capabilities.reason||'검증된 원천·QC 판본·담당 승인 연결이 필요합니다.'}</p></details>
    <div className="qc-actor"><span>{sessionState}</span><button disabled={checking} onClick={checkActor}><RefreshCw size={12}/>{checking?'확인 중':'담당자 확인'}</button></div>
    <div className="qc-review-actions">{actions.map(([action,label])=>{const gate=qcActionAvailability(packet,actor,action);return <button key={action} disabled={!gate.enabled} title={gate.reason} aria-describedby="qc-action-reason" className={action==='approve'?'primary':''}>{label}</button>;})}</div>
    <p id="qc-action-reason" className="qc-panel-note">{qcActionAvailability(packet,actor,'approve').reason} 기존 승인 작업은 아래 업무 도구에서 권한·추천 hash·revision을 확인합니다.</p>
  </section>;
}

export function QCSelectedSeries({packet,selected,scope,revision}:{packet:QCWorkspacePacket|null;selected?:QCCase;scope:QCScope;revision:number}){
  const [result,setResult]=useState<{key:string;data?:any;error?:string}|null>(null),[retry,setRetry]=useState(0);
  const snapshot=packet?.snapshot||'',station=selected?.station_code||'',item=selected?.item_code||'',month=selected?.observed_time_raw.slice(0,7)||'';
  const depth=useMemo(()=>[selected?.depth_step??null,selected?.depth_from??null,selected?.depth_to??null],[selected?.depth_step,selected?.depth_from,selected?.depth_to]);
  const key=JSON.stringify([selected?.case_key,snapshot,scope.source,scope.from,scope.to,scope.day,scope.time,depth,revision,retry]);
  const query=new URLSearchParams({source:scope.source,station,item,month,as_of_day:scope.day,as_of_time:scope.time,limit:'240',offset:'0',tail:'true'});['depth_step','depth_from','depth_to'].forEach((name,index)=>{if(depth[index]!=null)query.set(name,String(depth[index]));});
  const path=query.toString();
  useEffect(()=>{setResult(null);if(!station||!item||!snapshot)return;const control=new AbortController();apiFetch(API_BASE_URL+'/lake/series?'+path,{signal:control.signal}).then(async response=>{if(!response.ok)throw new Error('HTTP '+response.status);return response.json();}).then(data=>{if(!control.signal.aborted)setResult({key,data});}).catch(error=>{if(!control.signal.aborted)setResult({key,error:'선택 사례 시계열 조회 실패: '+error.message});});return()=>control.abort();},[path,key,station,item,snapshot]);
  const current=result?.key===key?result:null;
  const valid=current?.data&&matchesLakeSeries(current.data,{source:scope.source,from:scope.from,to:scope.to,day:scope.day,time:scope.time,station,item,month,depth,snapshot,limit:240,offset:0,tail:true});
  if(!selected)return null;
  return <section className="qc-panel qc-selected-series" aria-label="선택 품질 사례 실제 시계열"><QCPanelHeading title={'선택 사례의 실제 관측값 · '+observationItemLabel(item)} note="같은 원천·관측소·항목·수심의 원문 시계열입니다. AI 예측·승인 QC는 포함하지 않습니다."><span className="qc-pill">공통 기준 {scope.day} {scope.time}</span></QCPanelHeading>
    {current?.error||current?.data&&!valid?<p role="alert" className="qc-error">{current.error||'원천·관측소·수심·기준시각 응답이 일치하지 않습니다.'}<button className="qc-link-button" onClick={()=>setRetry(v=>v+1)}>시계열 다시 조회</button></p>:valid?<ObservationSeriesChart key={key} rows={current!.data.rows} item={item} label={observationItemLabel(item)}/>:<p role="status" className="qc-empty">실제 관측 시계열 조회 중…</p>}
    <details className="qc-source-proof"><summary><ShieldCheck size={13}/>선택 원천 행·파일·hash 확인</summary><dl><dt>원천 파일</dt><dd>{selected.file} · 행 {selected.file_row_number}</dd><dt>원본 SHA-256</dt><dd>{selected.source_sha256}</dd><dt>Parquet SHA-256</dt><dd>{selected.parquet_sha256}</dd><dt>관측시각 / 값</dt><dd>{selected.observed_time_raw} / {selected.value_raw===null?'NULL':JSON.stringify(selected.value_raw)}</dd><dt>수심 원문</dt><dd>{[selected.depth_step,selected.depth_from,selected.depth_to].map(qcLiteralLabel).join(' / ')}</dd><dt>원문 QC / MQ / N1 QC</dt><dd className="qc-raw-literal">{[selected.source_qc_raw,selected.source_mq_raw,selected.source_n1_qc_raw].map(qcLiteralLabel).join(' / ')}</dd><dt>단위·시간대·물리 센서</dt><dd>미확정 · 현재 메타데이터로 과거 원천을 덮어쓰지 않습니다.</dd></dl></details>
  </section>;
}

export function QCDailyQueue({packet,selectedId,onSelect,onPage}:{packet:QCDailyOverview|null;selectedId:string;onSelect:(id:string)=>void;onPage:(offset:number)=>void}){
 const [search,setSearch]=useState('');
 const rawRows=packet?.review_queue.rows||[],rows=rawRows.filter(row=>!search.trim()||[row.station_id,row.station_name,row.variable_code,row.rule_name,row.review_status,packet?.flag_catalog.find(f=>f.code===row.flag)?.label].some(value=>String(value||'').toLocaleLowerCase('ko-KR').includes(search.trim().toLocaleLowerCase('ko-KR'))));
 const queue=packet?.review_queue,total=queue?.total??queue?.validated_subset_total??0,page=queue?Math.floor(queue.offset/queue.limit)+1:1,pages=queue?Math.max(1,Math.ceil(total/queue.limit)):1,partial=queue?.state==='PARTIAL';
 return <section className="qc-panel qc-cases qc-priority-queue" aria-label="우선 품질 검토 Queue"><QCPanelHeading title="주요 이상 사례 · 검토 Queue" note="저장된 Rule QC 후보를 우선순위로 조회합니다. 원문 최신 표본을 이상 후보로 세지 않습니다."><span className="qc-pill">{qcNumber(queue?.total)}건</span></QCPanelHeading>
 <div className="qc-case-tools"><label><Search size={13}/><input aria-label="검토 Queue 현재 페이지 검색" value={search} onChange={e=>setSearch(e.target.value)} placeholder="현재 페이지의 관측소·Rule 검색"/></label><span className="qc-pill">BAD → Suspect → 최근</span></div>
 <div className="qc-case-scroll"><table><thead><tr><th>관측소</th><th>항목</th><th>발생시각</th><th>실제값</th><th>QC Flag</th><th>Rule</th><th>Severity</th><th>검토상태</th></tr></thead><tbody>{rows.map(row=>{const flag=packet?.flag_catalog.find(f=>f.code===row.flag);return <tr key={row.id} className={row.id===selectedId?'selected':''} onClick={()=>onSelect(row.id)}><td><button aria-label={(row.station_name||row.station_id)+' '+observationItemLabel(row.variable_code)+' QC 상세검토'} aria-pressed={row.id===selectedId} onClick={e=>{e.stopPropagation();onSelect(row.id);}}>{row.station_name||packet?.filters?.stations.find(s=>s.station_id===row.station_id)?.station_name||row.station_id}</button></td><td title={row.variable_code}>{observationItemLabel(row.variable_code)}</td><td title={row.observation_time}>{row.observation_time.slice(5,16).replace('T',' ')}</td><td>{qcValueNumber(row.value)}</td><td title={flag?.definition_source}><span className="qc-state" style={{color:flag?.color,background:flag?flag.color+'18':undefined}}>{flag?.label||row.flag}</span></td><td title={row.rule_name}>{row.rule_name||'Rule 상세에서 확인'}</td><td>{packet?.flag_catalog.find(f=>f.code===row.severity)?.label||row.severity||'—'}</td><td>{qcStateLabel(row.review_status)}</td></tr>;})}{!rows.length&&<tr><td colSpan={8} className="qc-empty">{packet?rawRows.length?'검색에 맞는 현재 페이지 후보 없음':'선택 시간창에 검토가 필요한 저장 후보 없음':'검토 후보 조회 중'}</td></tr>}</tbody></table></div>
 <div className="qc-table-pagination"><span>{queue?.rows.length?queue.offset+1:0} - {queue?queue.offset+queue.rows.length:0} / {partial?'전체 미확정 · 확인된 '+qcNumber(total):qcNumber(queue?.total)}건</span><nav aria-label="검토 Queue 페이지"><button aria-label="이전 검토 Queue" disabled={!queue||queue.offset===0} onClick={()=>onPage(Math.max(0,queue!.offset-queue!.limit))}><ChevronLeft size={13}/></button><span>{page}/{partial?'—':pages}</span><button aria-label="다음 검토 Queue" disabled={!queue||queue.offset+queue.limit>=total||queue.offset+queue.limit>1000} onClick={()=>onPage(queue!.offset+queue!.limit)}><ChevronRight size={13}/></button></nav></div>
 <p className="qc-panel-note">{partial?'일부 권위·자료만 확인하여 전체 후보 수는 미확정입니다. ':''}후보를 선택하면 전후 시계열·실제 Threshold·저장된 AI·장비·Evidence·검토 이력을 상세 Drawer에서 확인합니다.</p></section>;
}

export function QCDailyReviewPrompt({packet,onSelect}:{packet:QCDailyOverview|null;onSelect:(id:string)=>void}){
 const first=packet?.review_queue.rows[0];
 return <section className="qc-panel qc-review" aria-label="QC 상세검토 지원"><QCPanelHeading title="QC 상세검토 지원"><span className="qc-pill">담당자 검토</span></QCPanelHeading>
 <div className="qc-review-prompt"><BrainCircuit size={23}/><p>지금 확인해야 할 후보를 선택하면 “왜 이상인가?”를 실제 관측값과 근거로 검토합니다.</p></div>
 <ol className="qc-detail-steps"><li><b>1</b><div><strong>실제 시계열·지연·Gap</strong><p>발생 전후 ±2시간 · 실제 값 유지 · 예측 보간 없음</p></div></li><li><b>2</b><div><strong>Rule·AI·장비·Evidence</strong><p>실제 Threshold/Version · 저장된 AI가 있을 때만 비교</p></div></li><li><b>3</b><div><strong>담당자 결정·처리 이력</strong><p>권한·workflow revision·hash를 확인한 기존 승인 절차</p></div></li></ol>
 {first?<button className="qc-primary-button qc-full-button" onClick={()=>onSelect(first.id)}>최우선 후보 상세검토<ArrowRight size={13}/></button>:<div className="qc-no-candidates"><CheckCircle2 size={17}/><span>{packet?'선택 시간창에 검토 후보 없음':'후보 현황 조회 중'}</span></div>}
 <p className="qc-panel-note">후보 없음은 관측망 전체 정상 판정을 뜻하지 않습니다. 확인된 자료·Rule·수신 이력 범위는 상단 상태와 근거에서 확인하세요.</p><Link to="/ai-insights" className="qc-link-button">장기 Drift·모델·Residual 분석은 AI 인사이트에서<ArrowRight size={12}/></Link></section>;
}
