import {useEffect,useMemo,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Search,ChevronRight,ShieldCheck,CircleAlert,TriangleAlert,Cloud,ClipboardClock,CheckCircle2,Database,RefreshCw,ArrowRight} from 'lucide-react';
import {API_BASE_URL,apiFetch} from '../api/client';
import WorkflowReviewPanel from './WorkflowReviewPanel';
import {observationItemLabel} from '../data/observationAvailability';
import {qcDailyRequest,qcDailyQuery,validQCContext,validQCDailyOverview,qcDailyMetricText,qcLiteralLabel,qcNumber,qcStateLabel,type QCContext,type QCDailyOverview} from '../data/qcWorkspace';
import {QCDailyDistribution,QCDailyTrend,QCDailyRules,QCDailyMatrix} from './QCWorkspaceCharts';
import {QCDailyQueue,QCDailyReviewPrompt} from './QCCaseReview';
import QCCandidateDrawer from './QCCandidateDrawer';
import '../styles/qc.css';

const ranges=[['today','오늘'],['yesterday','어제'],['7d','최근 7일'],['30d','최근 30일'],['custom','사용자 지정']];
const nativeDayOffset=(day:string,delta:number)=>{const d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+delta);return d.toISOString().slice(0,10);};
export default function QCWorkspace(){
 const [search,setSearch]=useSearchParams(),[context,setContext]=useState<QCContext|null>(null),[contextError,setContextError]=useState(''),[contextRevision,setContextRevision]=useState(0);
 // Router search callbacks are not queued like React state. Accumulate changes until the URL commits.
 const searchFrame=useRef({observed:search.toString(),pending:new URLSearchParams(search)});
 if(searchFrame.current.observed!==search.toString())searchFrame.current={observed:search.toString(),pending:new URLSearchParams(search)};
 const [revision,setRevision]=useState(0),[frame,setFrame]=useState<{key:string;packet:QCDailyOverview}|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[dateError,setDateError]=useState(''),[customOpen,setCustomOpen]=useState(false),[draft,setDraft]=useState({start:'',end:''}),[stationSearch,setStationSearch]=useState('');
 const request=useMemo(()=>qcDailyRequest(search,context),[search,context]),path=request?qcDailyQuery(request):'',key=path+'|'+revision;
 const packet=frame?.key===key?frame.packet:null,archive=request?.source!=='REGISTERED'&&Boolean(request),candidateId=search.get('candidate')||'';
 const refresh=()=>{setContextRevision(v=>v+1);setRevision(v=>v+1);};
 const update=(changes:Record<string,string>,replace=false)=>{const next=new URLSearchParams(searchFrame.current.pending);for(const [name,value] of Object.entries(changes)){if(name==='station')next.delete('station_id');if(name==='item')next.delete('variable_code');if(value)next.set(name,value);else next.delete(name);}searchFrame.current.pending=next;setSearch(next,{replace});};
 useEffect(()=>{const c=new AbortController();setContext(null);setContextError('');apiFetch(API_BASE_URL+'/qc/context',{signal:c.signal}).then(async r=>{if(!r.ok)throw new Error('운영 시계 조회 실패 (HTTP '+r.status+')');return r.json();}).then(data=>{if(c.signal.aborted)return;if(!validQCContext(data))throw new Error('백엔드 운영 시계·원천·플래그 정의 확인 실패');setContext(data);}).catch(e=>{if(!c.signal.aborted)setContextError(e.message);});return()=>c.abort();},[contextRevision]);
 useEffect(()=>{setFrame(null);setError('');if(!request){setLoading(false);return;}const c=new AbortController();setLoading(true);apiFetch(API_BASE_URL+'/qc/overview?'+path,{signal:c.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:'품질 조회 실패 (HTTP '+r.status+')');return data;}).then(data=>{if(c.signal.aborted)return;if(!validQCDailyOverview(data,request))throw new Error('원천·시간창·플래그·분모·후보 응답이 조회 조건과 일치하지 않습니다.');setFrame({key,packet:data});}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[path,key,request]);
 useEffect(()=>{if(packet)setDraft({start:packet.window.start.slice(0,19).replace(' ','T'),end:packet.window.end.slice(0,19).replace(' ','T')});},[packet]);
 const chooseRange=(range:string)=>{setDateError('');if(range==='custom'){setCustomOpen(true);return;}setCustomOpen(false);const pending=searchFrame.current.pending,active=qcDailyRequest(pending,context);if(active&&active.source!=='REGISTERED'){const ceiling=pending.get('as_of_day')||active.dateTo?.slice(0,10)||'2026-07-09',clock=pending.get('as_of_time')||active.dateTo?.slice(11)||'15:41:20';const start=range==='yesterday'?nativeDayOffset(ceiling,-1):range==='7d'?nativeDayOffset(ceiling,-6):range==='30d'?nativeDayOffset(ceiling,-29):ceiling;const end=range==='yesterday'?start+' 23:59:59.999999':ceiling+' '+clock;update({preset:'custom',range,date_from:start+' 00:00:00',date_to:end,queue_offset:'',candidate:''});}else update({preset:range,range:'',date_from:'',date_to:'',queue_offset:'',candidate:''});};
 const applyCustom=(e:React.FormEvent)=>{e.preventDefault();if(!draft.start||!draft.end||draft.start>draft.end){setDateError('시작·종료 시각을 확인하세요.');return;}const offset=archive?'':packet?.window.offset||context?.offset;if(!archive&&!offset){setDateError('백엔드 시간 기준을 먼저 확인하세요.');return;}const full=(v:string)=>(v.length===16?v+':00':v)+(offset||'');update({preset:'custom',range:'custom',date_from:full(draft.start),date_to:full(draft.end),candidate:'',queue_offset:''});setCustomOpen(false);setDateError('');};
 const clearGrain=(changes:Record<string,string>)=>update({...changes,queue_offset:'',candidate:''});
 const options=packet?.filters,stations=options?.stations||[],variables=options?.variables||[];
 const source=request?.source||'REGISTERED',activeRange=archive?(search.get('range')||(search.has('date_from')?'custom':'today')):request?.preset||'today';
 const stationMatches=stations.filter(row=>[row.station_id,row.station_name].some(v=>v.toLocaleLowerCase('ko-KR').includes(stationSearch.trim().toLocaleLowerCase('ko-KR'))));
 const cards=[['normal','정상률',ShieldCheck,'mint'],['suspect','주의 / Suspect 비율',CircleAlert,'amber'],['bad','BAD 비율',TriangleAlert,'rose'],['missing','결측률',Cloud,'violet'],['pending','승인 / 검토 대기',ClipboardClock,'blue'],['completed','품질처리 완료',CheckCircle2,'violet']] as const;
 const scopeText=[options?.seas.find(row=>row.value===request?.sea)?.label||request?.sea||'전체 해역',options?.networks.find(row=>row.value===request?.network)?.label||request?.network||'전체 관측망',stations.find(row=>row.station_id===request?.station)?.station_name||request?.station||'전체 관측소',request?.item?observationItemLabel(request.item):'전체 항목'].join(' · ');
 const detailSelection=candidateId&&packet&&(candidateId.startsWith('archive:')?packet.archive_samples?.rows.some(row=>row.id===candidateId):packet.review_queue.rows.some(row=>row.id===candidateId));
 return <div className="qc-workspace"><div className="qc-masthead"><div className="qc-global-search"><Search size={16}/><input aria-label="QC 관측소 검색" placeholder="관측소를 검색해 운영 품질을 확인하세요…" value={stationSearch} onChange={e=>setStationSearch(e.target.value)}/>{stationSearch.trim()&&<div className="qc-search-results" role="listbox" aria-label="QC 관측소 검색 결과">{stationMatches.slice(0,8).map(row=><button key={row.station_id} role="option" aria-selected={row.station_id===request?.station} onClick={()=>{clearGrain({station:row.station_id,item:''});setStationSearch('');}}>{row.station_name}<small>{row.station_id}</small></button>)}{!stationMatches.length&&<p>현재 범위의 일치 관측소 없음</p>}</div>}</div><p>데이터로 만드는<br/><strong>안전한 바다, 지속 가능한 미래</strong></p><span><Database size={13}/>{archive?'보존 원천 재생':'일일 운영 QC'}</span></div>
 <div className="qc-page-body"><div className="qc-breadcrumb"><Link to="/">홈</Link><ChevronRight size={11}/><span>품질 현황</span><time>{packet?'조회 기준 '+packet.window.as_of:'백엔드 운영 시계 확인 중'}</time></div>
 <header className="qc-page-heading qc-daily-heading"><div className="qc-title"><p>QUALITY CONTROL</p><h1>품질 현황 (QC)</h1><span>오늘 들어온 자료의 1차 품질과 우선 검토 대상을 빠르게 확인합니다.</span></div><Link className="qc-ai-entry" to="/ai-insights"><span>AI</span><div><strong>AI 분석 인사이트</strong><small>장기 Drift·모델·Residual 분석은<br/>AI 인사이트에서 확인하세요.</small></div><ChevronRight size={18}/></Link><div className="qc-daily-date-summary"><strong>{archive?'과거 재현 · 보존 원천 기준일':(ranges.find(([key])=>key===activeRange)?.[1]||'선택 기간')+' 국가해양관측망 QC'}</strong><p>{packet?packet.window.start+' ~ '+packet.window.end:context?context.today+' 00:00 ~ 백엔드 현재시각':'운영 시간 기준 조회 중'}</p><small>{qcStateLabel(packet?.window.clock_basis||context?.clock_basis||'시간 기준 미확인')}{packet?.window.offset?' · '+packet.window.offset:''}</small></div></header>
 <div className="qc-range-bar" role="group" aria-label="QC 빠른 조회기간">{ranges.map(([range,label])=><button key={range} aria-pressed={activeRange===range} onClick={()=>chooseRange(range)} disabled={!context&&!archive}>{archive&&range==='today'?'기준일':archive&&range==='yesterday'?'기준일 전날':label}</button>)}<label>자료 경로<select aria-label="QC 자료 경로" value={source} onChange={e=>update({source:e.target.value==='REGISTERED'?'':e.target.value,preset:e.target.value==='REGISTERED'?'today':'custom',date_from:'',date_to:'',from:'',to:'',as_of_day:'',as_of_time:'',station:'',item:'',flag:'',queue_offset:'',candidate:''})}>{(context?.sources||[{value:source,label:source}]).map(row=><option key={row.value} value={row.value}>{row.label}</option>)}</select></label><button className="qc-refresh" aria-label="운영 QC 새로고침" disabled={loading} onClick={refresh}><RefreshCw size={14} className={loading?'animate-spin':''}/></button></div>
 {customOpen&&<form className="qc-custom-window" onSubmit={applyCustom}><label>시작 시각<input aria-label="QC 사용자 지정 시작" type="datetime-local" step="1" required value={draft.start} onChange={e=>setDraft(d=>({...d,start:e.target.value}))}/></label><label>종료 시각<input aria-label="QC 사용자 지정 종료" type="datetime-local" step="1" required value={draft.end} onChange={e=>setDraft(d=>({...d,end:e.target.value}))}/></label><span>{archive?'원천 native 시계 · 시간대 미확정':packet?.window.offset||context?.offset}</span><button className="qc-primary-button" type="submit">기간 적용</button></form>}{dateError&&<p role="alert" className="qc-error">{dateError}</p>}
 <div className="qc-scope-controls"><label>해역<select aria-label="QC 해역" value={request?.sea||''} disabled={loading} onChange={e=>clearGrain({sea:e.target.value,station:'',item:''})}><option value="">전체 해역</option>{options?.seas.map(row=><option key={row.value} value={row.value}>{row.label}</option>)}{request?.sea&&!options?.seas.some(row=>row.value===request.sea)&&<option value={request.sea}>{request.sea}</option>}</select></label><label>관측망<select aria-label="QC 관측망" value={request?.network||''} disabled={loading} onChange={e=>clearGrain({network:e.target.value,station:'',item:''})}><option value="">전체 관측망</option>{options?.networks.map(row=><option key={row.value} value={row.value}>{row.label}</option>)}{request?.network&&!options?.networks.some(row=>row.value===request.network)&&<option value={request.network}>{request.network}</option>}</select></label><label>관측소<select aria-label="QC 관측소" value={request?.station||''} disabled={loading} onChange={e=>clearGrain({station:e.target.value,item:''})}><option value="">전체 관측소</option>{stations.map(row=><option key={row.station_id} value={row.station_id}>{row.station_name} ({row.station_id})</option>)}{request?.station&&!stations.some(row=>row.station_id===request.station)&&<option value={request.station}>{request.station}</option>}</select></label><label>관측항목<select aria-label="QC 관측항목" value={request?.item||''} disabled={loading} onChange={e=>clearGrain({item:e.target.value})}><option value="">전체 항목</option>{variables.map(row=><option key={row.variable_code} value={row.variable_code}>{row.label||observationItemLabel(row.variable_code)}</option>)}{request?.item&&!variables.some(row=>row.variable_code===request.item)&&<option value={request.item}>{observationItemLabel(request.item)}</option>}</select></label><button className="qc-link-button" onClick={()=>clearGrain({station:'',item:'',network:'',sea:'',flag:''})}>필터 초기화</button></div>
 <p className="qc-scope-note" aria-live="polite">{scopeText} · {packet?qcNumber(packet.total_observations)+'건 · '+(packet.window.granularity==='hour'?'시간':'일')+' 단위 집계':'같은 시간창으로 모든 화면 조회'}{request?.flag?' · 상태 '+(packet?.flag_catalog.find(f=>f.code===request.flag)?.label||request.flag):''}</p>
 {contextError&&<div role="alert" className="qc-error-banner"><span>{contextError}</span><button onClick={()=>setContextRevision(v=>v+1)} className="qc-primary-button">운영 시계 다시 확인</button></div>}{loading&&<div role="status" className="qc-loading">같은 원천·시간창·조건으로 품질 집계와 검토 후보를 조회하고 있습니다…</div>}{error&&<div role="alert" className="qc-error-banner"><span>{error}</span><button className="qc-primary-button" onClick={refresh}>다시 조회</button></div>}
 {packet&&<div className="qc-data-state"><strong>{packet.states?.overall==='PARTIAL'?'일부 근거만 확인됨':packet.total_observations===0?'선택 시간창 데이터 없음':archive?'보존 원문 재생 조회':'확인된 운영 자료 조회'}</strong><span>{String(packet.states?.message||packet.provenance.note||'원천·QC·수신시각 확인 범위는 분모와 근거에서 확인하세요.')} · AI {qcStateLabel(packet.states.ai)} · 모델 {qcStateLabel(packet.states.model)} · Evidence {qcStateLabel(packet.states.evidence)}</span></div>}
 <div className="qc-summary-cards">{cards.map(([name,label,Icon,tone],index)=>{const view=error||contextError?{value:'조회 실패',count:'자료 재조회 필요'}:qcDailyMetricText(packet?.summary[name],index<4);return <article key={name} className={'qc-summary-card '+tone}><div><span className="qc-summary-icon"><Icon size={23}/></span><div><h2>{name==='missing'&&packet?.summary.missing.stage==='RAW_VALUE_LITERAL'?'원시 빈값률':name==='completed'&&packet?.summary.completed.stage==='RECOMMENDATION_WORKFLOW'?'권고 검토 작업 완료':label}</h2><strong className={view.value==='데이터 없음'?'qc-no-data-value':''}>{view.value}</strong></div></div><p>{view.count}</p><small>{packet?.summary[name]?.stage==='RAW_VALUE_LITERAL'?'원문 빈값 · 수신 결측과 별도':qcStateLabel(packet?.summary[name]?.stage||'QC 단계 조회 중')}</small></article>;})}</div>
 <div className="qc-dashboard-grid"><QCDailyDistribution packet={packet} onFlag={flag=>clearGrain({flag})}/><QCDailyTrend packet={packet}/><QCDailyRules packet={packet}/><QCDailyMatrix packet={packet} onSelect={(station,item)=>clearGrain({station,item})}/><QCDailyQueue packet={packet} selectedId={candidateId} onSelect={id=>update({candidate:id})} onPage={offset=>update({queue_offset:String(offset),candidate:''})}/><QCDailyReviewPrompt packet={packet} onSelect={id=>update({candidate:id})}/></div>
 {archive&&<details className="qc-panel qc-archive-samples"><summary><Database size={15}/>보존 원천 최신 표본 · 이상 검토 Queue와 별도<span>{qcNumber(packet?.archive_samples?.total_matching_rows)} 원문 행 중 최대 15행</span></summary><p className="qc-panel-note">미해석 원문을 이상·정상·승인 후보로 바꾸지 않습니다. 선택하면 원문 상세를 조회합니다.</p><div className="qc-case-scroll"><table><thead><tr><th>관측소</th><th>항목</th><th>원문 시각</th><th>실제값</th><th>원문 QC</th></tr></thead><tbody>{packet?.archive_samples?.rows.map(row=><tr key={row.id}><td><button onClick={()=>update({candidate:row.id})}>{row.station_name||row.station_code||row.station_id}</button></td><td>{observationItemLabel(row.item_code||row.variable_code)}</td><td>{row.observed_time_raw||row.observation_time}</td><td>{row.value_raw===null?'NULL':String(row.value_raw)}</td><td className="qc-raw-literal">{qcLiteralLabel(row.source_qc_raw)}</td></tr>)}{packet&&!packet.archive_samples?.rows.length&&<tr><td colSpan={5} className="qc-empty">선택 시간창 원문 표본 없음</td></tr>}</tbody></table></div></details>}
 <details id="qc-workflow-tools" className="qc-panel qc-workflow-tools"><summary><ShieldCheck size={16}/>기존 근거 통합·담당자 승인 업무 도구<span>기존 권한·revision·hash 확인</span></summary><WorkflowReviewPanel/></details>
 <details className="qc-panel qc-provenance"><summary><Database size={15}/>시간 기준·원천·Flag·분모·조회 근거</summary>{packet?<><p>원천 {packet.source} · 검증본 {packet.snapshot||'운영 등록 원장'} · {packet.window.clock_basis}</p><p>{packet.window.start} ~ {packet.window.end} · 기준 {packet.window.as_of}</p><pre>{JSON.stringify({states:packet.states,provenance:packet.provenance,flag_catalog:packet.flag_catalog,window_id:packet.window.window_id,result_sha256:packet.result_sha256},null,2)}</pre></>:<p>조회 근거 확인 전</p>}</details>
 <footer className="qc-footer"><span><CheckCircle2 size={12}/>{error?'조회 실패':loading?'집계 조회 중':packet?'공통 시간창의 검증된 QC 자료':'운영 시계 확인 전'}</span><Link to="/ai-insights">장기 분석으로 이동<ArrowRight size={11}/></Link></footer>
 </div>{detailSelection&&packet&&request&&<QCCandidateDrawer id={candidateId} overview={packet} request={request} onClose={()=>update({candidate:''})} onChanged={()=>setRevision(v=>v+1)}/>}</div>;
}
