import {useRef,useState} from 'react';
import {ResponsiveContainer,PieChart,Pie,Cell,Tooltip,AreaChart,Area,LineChart,Line,XAxis,YAxis,CartesianGrid} from 'recharts';
import {ChevronLeft,ChevronRight,Info,Layers3} from 'lucide-react';
import {observationItemLabel} from '../data/observationAvailability';
import {qcLiteralLabel,qcNumber,qcPercent,qcReasonText,qcTrendRows,qcPage,nextQCHeatmapCell,qcStateLabel,type QCWorkspacePacket,type QCDistribution,type QCDailyOverview,type QCFlag,type QCDailyCounts} from '../data/qcWorkspace';

const COLORS=['#148bfa','#16b8b1','#f4ab38','#926be9','#94a3b8','#fd8a67','#4973cc','#b1c5da'];
const fieldName=(field:string)=>({qc_raw:'원문 QC',QC_FLAG:'원문 QC',mq_raw:'원문 MQ',MQC_FLAG:'원문 MQ',n1_aqc_raw:'원문 N1 QC',N1_AQC_FLAG:'원문 N1 QC'} as Record<string,string>)[field]||field;
export const QCPanelHeading=({title,note,children}:{title:string;note?:string;children?:React.ReactNode})=><div className="qc-panel-heading"><h2><Layers3 size={18}/>{title}{note&&<span title={note} aria-label={note}><Info size={13}/></span>}</h2>{children}</div>;

export function QCDistributionPanel({packet,onLiteral,selectedField,selectedLiteral,selectedNull}:{packet:QCWorkspacePacket|null;onLiteral:(row:QCDistribution|null)=>void;selectedField:string;selectedLiteral:string|null;selectedNull:boolean}){
  const [chosenField,setChosenField]=useState('qc_raw'),[view,setView]=useState('literal');
  const fields=[...new Set(packet?.distribution.map(row=>row.field)||[])];
  const field=fields.includes(chosenField)?chosenField:fields[0]||'source_qc_raw';
  const rows=(packet?.distribution||[]).filter(row=>row.field===field);
  const unassessed=packet?.cards.unassessed;
  const chartRows=view==='literal'?rows.map((row,index)=>({...row,name:qcLiteralLabel(row.literal),color:COLORS[index%COLORS.length]})):unassessed?.count?[{name:'미해석 원문 QC',count:unassessed.count,color:'#99b4d3'}]:[];
  const picked=(row:QCDistribution)=>row.field===selectedField&&(selectedNull?row.literal===null:row.literal===selectedLiteral);
  return <section className="qc-panel qc-distribution" aria-label="품질 플래그 분포"><QCPanelHeading title="품질 플래그 분포" note="원천 문자열 분포입니다. 코드북을 확인하기 전에는 정상·주의·BAD 의미를 부여하지 않습니다."><button onClick={()=>onLiteral(null)} disabled={!selectedField} className="qc-link-button">전체 원문 보기<ChevronRight size={12}/></button></QCPanelHeading>
    <div className="qc-tabs" role="tablist" aria-label="플래그 분포 보기">{[['literal','원문 코드'],['unknown','해석 상태']].map(([id,label])=><button key={id} role="tab" aria-selected={view===id} onClick={()=>setView(id)}>{label}</button>)}</div>
    {view==='literal'&&fields.length>1&&<div className="qc-field-tabs" role="group" aria-label="원문 플래그 필드">{fields.map(name=><button key={name} aria-pressed={field===name} onClick={()=>setChosenField(name)}>{fieldName(name)}</button>)}</div>}
    <div className="qc-donut-layout"><div className="qc-donut"><div className="qc-donut-center"><span>{view==='literal'?'보유 원문 행':'QC 의미 미해석'}</span><strong>{packet?qcNumber(packet.cards.held_rows):'—'}</strong><small>행 · 중복 원천 포함</small></div>{chartRows.length?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chartRows} dataKey="count" nameKey="name" innerRadius="67%" outerRadius="91%" paddingAngle={chartRows.length>1?1:0} stroke="white" isAnimationActive={false}>{chartRows.map((row,index)=><Cell key={index} fill={row.color}/>)}</Pie><Tooltip formatter={(value:any,name:any)=>[qcNumber(Number(value))+'행',name]}/></PieChart></ResponsiveContainer>:<p className="qc-chart-empty">{packet?'집계할 원문 없음':'원문 집계 조회 중'}</p>}</div>
      <div className="qc-distribution-list" role="list" aria-label="원문 플래그 범례">{view==='literal'?rows.map((row,index)=><button role="listitem" key={JSON.stringify([row.field,row.literal])} aria-pressed={picked(row)} onClick={()=>onLiteral(picked(row)?null:row)} title={`${fieldName(row.field)} ${qcLiteralLabel(row.literal)} · ${row.count} / ${row.denominator}행 · 의미 미해석`}><i style={{background:COLORS[index%COLORS.length]}}/><span>{qcLiteralLabel(row.literal)}</span><b>{qcPercent(row.rate)}</b><small>{qcNumber(row.count)}행</small></button>):<div className="qc-unknown-legend"><i/><span>의미 미해석</span><b>{qcPercent(unassessed?.rate)}</b><small>{qcNumber(unassessed?.count)}행</small></div>}{view==='literal'&&!rows.length&&<p className="qc-empty">선택 범위의 플래그 집계가 없습니다.</p>}</div></div>
    <p className="qc-panel-note">{view==='literal'?fieldName(field)+' · 필드 분모 '+qcNumber(rows[0]?.denominator)+'행. 범례 선택은 최신 원문 사례만 필터합니다.':'코드 의미·판본·유효기간과 승인 이력이 확인되어야 품질 판정을 표시합니다.'}</p>
  </section>;
}

export function QCTrendPanel({packet,from,to}:{packet:QCWorkspacePacket|null;from:string;to:string}){
  const [view,setView]=useState('composition'),[visible,setVisible]=useState<Record<string,boolean>>({qc_presence_rate:true,missing_rate:true,unassessed_rate:true});
  const data=packet?qcTrendRows(packet.monthly,from,to):[];
  const legends=[['qc_presence_rate','원문 QC 표기율','#178aff'],['missing_rate','원시 결측표현율','#a17aea'],['unassessed_rate','QC 의미 미해석율','#8fa8c5']];
  return <section className="qc-panel qc-trend" aria-label="품질상태 변화 추이"><QCPanelHeading title="품질상태 변화 추이" note="해당 월의 보유 원문 행이 분모입니다. 자료 없는 월은 공백으로 남깁니다."><span className="qc-pill">월별</span></QCPanelHeading>
    <div className="qc-tabs" role="tablist" aria-label="품질 추이 보기">{[['composition','원문 값 구성'],['indicators','품질 지표']].map(([id,label])=><button key={id} role="tab" aria-selected={view===id} onClick={()=>setView(id)}>{label}</button>)}</div>
    <div className="qc-trend-chart">{packet&&data.some(row=>row.held_rows>0)?<ResponsiveContainer width="100%" height="100%">{view==='composition'?<AreaChart data={data} margin={{top:10,right:10,left:-15,bottom:0}}><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e7eef7"/><XAxis dataKey="month" tick={{fontSize:10,fill:'#7690ae'}}/><YAxis domain={[0,100]} unit="%" tick={{fontSize:10,fill:'#7690ae'}}/><Tooltip labelFormatter={value=>value+' · 월별 보유 행 기준'} formatter={(value:any,name:any)=>[qcPercent(Number(value)),name]}/><Area type="linear" dataKey="value_present_rate" name="원문 값 있음" stackId="raw" stroke="#28b8b1" fill="#91ded8" dot={{r:3}} connectNulls={false} isAnimationActive={false}/><Area type="linear" dataKey="missing_rate" name="원시 결측표현" stackId="raw" stroke="#a17aea" fill="#cbb7f4" dot={{r:3}} connectNulls={false} isAnimationActive={false}/></AreaChart>:<LineChart data={data} margin={{top:10,right:10,left:-15,bottom:0}}><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e7eef7"/><XAxis dataKey="month" tick={{fontSize:10,fill:'#7690ae'}}/><YAxis domain={[0,100]} unit="%" tick={{fontSize:10,fill:'#7690ae'}}/><Tooltip labelFormatter={value=>value+' · 월별 보유 행 기준'} formatter={(value:any,name:any)=>[qcPercent(Number(value)),name]}/>{legends.filter(([key])=>visible[key]).map(([key,label,color])=><Line key={key} type="linear" dataKey={key} name={label} stroke={color} strokeWidth={2} dot={{r:3}} connectNulls={false} isAnimationActive={false}/>)}</LineChart>}</ResponsiveContainer>:<p className="qc-chart-empty">{packet?'선택 기간의 월별 집계 없음':'추이 조회 중'}</p>}</div>
    {view==='composition'?<div className="qc-chart-legend"><span><i style={{background:'#28b8b1'}}/>원문 값 있음</span><span><i style={{background:'#a17aea'}}/>원시 결측표현</span></div>:<div className="qc-chart-legend" role="group" aria-label="품질 지표 선 표시">{legends.map(([key,label,color])=><button key={key} aria-pressed={!!visible[key]} onClick={()=>setVisible(p=>({...p,[key]:!p[key]}))}><i style={{background:visible[key]?color:'#dce5ef'}}/>{label}</button>)}</div>}
    <p className="qc-panel-note">승인 정상률·BAD 추이가 아닙니다. {packet?.cutoff_native}까지의 원문만 집계합니다.{data.filter(row=>row.held_rows>0).length===1?' 1개월은 실제 지표 점으로 표시합니다. 2개월 이상을 조회하면 월별 변화를 비교할 수 있습니다.':''}</p>
  </section>;
}

export function QCRulesPanel({packet}:{packet:QCWorkspacePacket|null}){
  const [opened,setOpened]=useState('');
  return <section className="qc-panel qc-rule-panel" aria-label="규칙 기반 QC 결과"><QCPanelHeading title="규칙 기반 QC 결과" note="엔진 규칙·등록 정의·선택 범위의 평가 결과를 별도로 표시합니다."><span className="qc-pill">엔진 {packet?.rules.catalog_count??'—'}종</span></QCPanelHeading>
    <div className="qc-rule-summary">등록 정의 {qcNumber(packet?.rules.registered_definition_count)}개 · 결과 {qcNumber(packet?.rules.result_count)}건 <span>원천 계약 확인 전</span></div>
    <div className="qc-rule-columns"><span>검사 유형</span><span>탐지 건수</span><span>평가 상태</span></div>
    <div className="qc-rule-list">{packet?.rules.items.map(rule=><div key={rule.kind}><button className="qc-rule-row" aria-expanded={opened===rule.kind} onClick={()=>setOpened(p=>p===rule.kind?'':rule.kind)}><span>{rule.name_ko}</span><span className="qc-rule-bar"><i style={{width:rule.status==='NOT_EVALUATED'?'0%':Math.min(100,100*(rule.anomaly_count||0)/Math.max(1,rule.evaluated_count||0))+'%'}}/><b>{rule.status==='NOT_EVALUATED'?'—':qcNumber(rule.anomaly_count)}</b></span><span className={'qc-state '+(rule.status==='NOT_EVALUATED'?'unknown':'evaluated')}>{rule.status==='NOT_EVALUATED'?'미평가':rule.status}</span></button>{opened===rule.kind&&<div className="qc-rule-detail"><strong>{rule.kind}</strong><p>평가 {qcNumber(rule.evaluated_count)}건 · 미평가 분모 {qcNumber(rule.not_evaluated_count)}</p><ul>{rule.reasons.map(reason=><li key={reason} title={reason}>{qcReasonText(reason)}</li>)}</ul></div>}</div>)}{!packet&&<p className="qc-empty">규칙 현황 조회 중</p>}</div>
    <p className="qc-panel-note">미평가는 탐지 0건을 의미하지 않습니다. 규칙을 선택해 필요한 근거를 확인하세요.</p>
  </section>;
}

export function QCMatrixPanel({packet,onSelect}:{packet:QCWorkspacePacket|null;onSelect:(station:string,item:string)=>void}){
  const [metric,setMetric]=useState('unassessed_rate'),[stationPage,setStationPage]=useState(1),[itemPage,setItemPage]=useState(1),[focusIndex,setFocusIndex]=useState(0);
  const container=useRef<HTMLDivElement>(null),rows=packet?.matrix||[];
  const stations=[...new Set(rows.map(row=>row.station_code))],items=[...new Set(rows.map(row=>row.item_code))];
  const stationSlice=qcPage(stations,stationPage,8),itemSlice=qcPage(items,itemPage,6);
  const focus=(event:React.KeyboardEvent,index:number)=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(event.key))return;event.preventDefault();const buttons=Array.from(container.current?.querySelectorAll<HTMLButtonElement>('button[data-qc-cell]')||[]),next=nextQCHeatmapCell(index,event.key,stationSlice.rows.length,itemSlice.rows.length,buttons.map(button=>!button.disabled));setFocusIndex(next);buttons[next]?.focus();};
  const label=({unassessed_rate:'QC 의미 미해석율',missing_rate:'원시 결측표현율',qc_presence_rate:'원문 QC 표기율'} as Record<string,string>)[metric];
  return <section className="qc-panel qc-matrix" aria-label="관측소별 항목 품질 현황"><QCPanelHeading title="관측소 × 관측항목 품질 현황" note="같은 관측소·항목의 모든 수심 원문 행을 분모로 합산합니다."><span className="qc-pill">{stations.length}개소 · {items.length}항목</span></QCPanelHeading>
    <label className="qc-matrix-select">표시 지표<select aria-label="히트맵 품질 지표" value={metric} onChange={event=>setMetric(event.target.value)}><option value="unassessed_rate">QC 의미 미해석율</option><option value="missing_rate">원시 결측표현율</option><option value="qc_presence_rate">원문 QC 표기율</option></select></label>
    <div className="qc-matrix-scroll" ref={container}><table><thead><tr><th>관측소</th>{itemSlice.rows.map(item=><th key={item} title={item}>{observationItemLabel(item)}</th>)}</tr></thead><tbody>{stationSlice.rows.map((station,rindex)=><tr key={station}><th>{rows.find(row=>row.station_code===station)?.station_name||station}</th>{itemSlice.rows.map((item,cindex)=>{
      const cell=rows.find(row=>row.station_code===station&&row.item_code===item),value=cell?.[metric as 'unassessed_rate'|'missing_rate'|'qc_presence_rate'],index=rindex*itemSlice.rows.length+cindex;
      const color=value==null?'#f0f4f9':metric==='unassessed_rate'?'#dbe6f1':`rgba(${metric==='missing_rate'?'157,112,217':'35,142,241'},${.08+.65*value/100})`;
      return <td key={item}><button data-qc-cell tabIndex={index===Math.min(focusIndex,stationSlice.rows.length*itemSlice.rows.length-1)?0:-1} onFocus={()=>setFocusIndex(index)} onKeyDown={event=>focus(event,index)} disabled={!cell} aria-label={`${cell?.station_name||station} ${observationItemLabel(item)} ${label} ${qcPercent(value)}`} title={cell?`${label}: ${qcPercent(value)} · 보유 ${qcNumber(cell.held_rows)}행 · ${cell.typed_grains.length}개 수심 묶음 · 클릭해 상세 조회`:'등록된 원문 자료 없음'} style={{background:color}} onClick={()=>onSelect(station,item)}>{qcPercent(value)}</button></td>;
    })}</tr>)}</tbody></table>{!rows.length&&<p className="qc-empty">{packet?'선택 조건의 관측항목 자료 없음':'품질 행렬 조회 중'}</p>}</div>
    <div className="qc-matrix-pagination"><span>{label} · ‘—’는 자료 없음</span><nav aria-label="히트맵 관측소 페이지"><button aria-label="이전 관측소 묶음" disabled={stationSlice.page<=1} onClick={()=>setStationPage(stationSlice.page-1)}><ChevronLeft size={12}/></button><span>{stationSlice.page}/{stationSlice.pages}</span><button aria-label="다음 관측소 묶음" disabled={stationSlice.page>=stationSlice.pages} onClick={()=>setStationPage(stationSlice.page+1)}><ChevronRight size={12}/></button></nav><nav aria-label="히트맵 항목 페이지"><button aria-label="이전 항목 묶음" disabled={itemSlice.page<=1} onClick={()=>setItemPage(itemSlice.page-1)}><ChevronLeft size={12}/></button><span>항목 {itemSlice.page}/{itemSlice.pages}</span><button aria-label="다음 항목 묶음" disabled={itemSlice.page>=itemSlice.pages} onClick={()=>setItemPage(itemSlice.page+1)}><ChevronRight size={12}/></button></nav></div>
    <p className="qc-panel-note">셀 선택으로 관측소·항목을 함께 조회합니다. 방향키로 이동할 수 있습니다. 색은 승인 정상·불량 판정이 아닙니다.</p>
  </section>;
}

const semanticKey=(flag:QCFlag):keyof QCDailyCounts|null=>({GOOD:'normal',NORMAL:'normal',SUSPECT:'suspect',BAD:'bad',MISSING:'missing',UNKNOWN:'unknown',UNASSESSED:'unknown'} as Record<string,keyof QCDailyCounts>)[flag.semantic.toUpperCase()]||null;
const semanticFlags=(packet:QCDailyOverview|null)=>{const found=new Map<keyof QCDailyCounts,QCFlag>();for(const flag of packet?.flag_catalog||[]){const key=semanticKey(flag);if(key&&!found.has(key))found.set(key,flag);}return [...found].map(([key,flag])=>({key,flag}));};
export function QCDailyDistribution({packet,onFlag}:{packet:QCDailyOverview|null;onFlag:(flag:string)=>void}){
 const rows=packet?.flag_distribution||[];
 return <section className="qc-panel qc-distribution" aria-label="선택 시간창 품질 플래그 분포"><QCPanelHeading title="품질 Flag 분포" note="현재 백엔드 플래그 정의와 1차 QC 단계의 집계입니다. 원천 문자 코드를 최종 승인 플래그로 해석하지 않습니다."><button className="qc-link-button" disabled={!packet?.scope.flag} onClick={()=>onFlag('')}>전체 상태 보기<ChevronRight size={12}/></button></QCPanelHeading>
 <div className="qc-donut-layout"><div className="qc-donut"><div className="qc-donut-center"><span>선택 시간창 자료</span><strong>{packet?qcNumber(packet.total_observations):'—'}</strong><small>{packet?.window.mode==='ARCHIVE'?'보존 원문 · 재생 조회':'원천·시각 계약을 확인한 자료'}</small></div>{rows.some(row=>row.count>0)?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="count" nameKey="label" innerRadius="67%" outerRadius="91%" stroke="white" paddingAngle={1} isAnimationActive={false}>{rows.map(row=><Cell key={row.code} fill={row.color}/>)}</Pie><Tooltip formatter={(value:any,label:any)=>[qcNumber(Number(value))+'건',label]}/></PieChart></ResponsiveContainer>:<p className="qc-chart-empty">{packet?'데이터 없음':'플래그 집계 조회 중'}</p>}</div>
 <div className="qc-distribution-list" aria-label="품질 플래그 범례">{rows.map(row=><button key={row.code} aria-pressed={packet?.scope.flag===row.code} onClick={()=>onFlag(packet?.scope.flag===row.code?'':row.code)} title={`${row.code} · ${row.stage} · ${row.count}/${row.denominator}건`}><i style={{background:row.color}}/><span>{row.label} <small>{row.code}</small></span><b>{qcPercent(row.rate)}</b><small>{qcNumber(row.count)}건</small></button>)}{packet&&!rows.length&&<p className="qc-empty">집계 대상 자료 없음</p>}</div></div>
 <p className="qc-panel-note">범례 선택은 카드·추이·규칙·행렬·검토 Queue에 동일하게 적용합니다. 플래그 정의와 표시색은 백엔드 catalog 기준입니다.</p></section>;
}

export function QCDailyTrend({packet}:{packet:QCDailyOverview|null}){
 const [view,setView]=useState('rates'),[hidden,setHidden]=useState<string[]>([]),flags=semanticFlags(packet);
 const isEmpty=!packet||!packet.quality_trend.some(row=>row.total>0);
 const toggle=(key:string)=>setHidden(previous=>previous.includes(key)?previous.filter(k=>k!==key):[...previous,key]);
 return <section className="qc-panel qc-trend" aria-label="선택 시간창 품질 변화 추이"><QCPanelHeading title="품질상태 변화 추이" note="오늘은 시간 단위, 7일·30일은 일 단위로 서버가 집계합니다. 원자료 보간·예측값 대체는 하지 않습니다."><span className="qc-pill">{packet?.window.granularity==='hour'?'시간별':'일별'}</span></QCPanelHeading><div className="qc-tabs" role="tablist" aria-label="품질 추이 지표">{[['rates','비율'],['counts','건수']].map(([key,label])=><button key={key} role="tab" aria-selected={view===key} onClick={()=>setView(key)}>{label}</button>)}</div>
 <div className="qc-trend-chart">{!isEmpty?<ResponsiveContainer width="100%" height="100%"><AreaChart data={packet!.quality_trend} margin={{top:10,right:10,left:-15,bottom:0}}><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e7eef7"/><XAxis dataKey="bucket" tickFormatter={value=>packet?.window.granularity==='hour'?String(value).slice(11,13)+'시':String(value).slice(5,10)} tick={{fontSize:10,fill:'#7690ae'}}/><YAxis domain={view==='rates'?[0,100]:['auto','auto']} unit={view==='rates'?'%':''} tick={{fontSize:10,fill:'#7690ae'}}/><Tooltip labelFormatter={(value,index:any)=>index?.[0]?.payload?.start+' ~ '+index?.[0]?.payload?.end||value} formatter={(value:any,label:any)=>[view==='rates'?qcPercent(Number(value)):qcNumber(Number(value))+'건',label]}/>{flags.filter(({key})=>!hidden.includes(key)).map(({key,flag})=><Area key={key} type="linear" dataKey={`${view}.${key}`} name={flag.label} stackId="qc" stroke={flag.color} fill={flag.color} fillOpacity={.35} dot={{r:2}} connectNulls={false} isAnimationActive={false}/>)}</AreaChart></ResponsiveContainer>:<p className="qc-chart-empty">{packet?'선택 시간창에 품질 자료 없음':'품질 추이 조회 중'}</p>}</div>
 <div className="qc-chart-legend" role="group" aria-label="추이 플래그 표시">{flags.map(({key,flag})=><button key={key} aria-pressed={!hidden.includes(key)} onClick={()=>toggle(key)}><i style={{background:hidden.includes(key)?'#dce5ef':flag.color}}/>{flag.label}</button>)}</div><p className="qc-panel-note">{packet?.window.start} ~ {packet?.window.end} · 비율 분모는 각 집계 구간의 자료입니다. 자료 없는 구간은 공백입니다.</p></section>;
}

export function QCDailyRules({packet}:{packet:QCDailyOverview|null}){
 const [open,setOpen]=useState(''),rules=packet?.rule_qc_counts.items||[];
 return <section className="qc-panel qc-rule-panel" aria-label="선택 시간창 규칙 기반 QC 결과"><QCPanelHeading title="규칙 기반 QC 결과" note="선택 시간창에 저장된 1차 Rule QC 결과입니다. 등록 정의와 엔진 구현을 실행 결과로 세지 않습니다."><span className="qc-pill">등록 {qcNumber(packet?.rule_qc_counts.registered_definition_count)}</span></QCPanelHeading><div className="qc-rule-columns"><span>탐지 Rule</span><span>이상 건수</span><span>전체 이상 비율</span></div><div className="qc-rule-list">{rules.map(rule=><div key={JSON.stringify([rule.rule_id,rule.rule_version])}><button className="qc-rule-row" aria-expanded={open===rule.rule_id} onClick={()=>setOpen(old=>old===rule.rule_id?'':rule.rule_id)}><span>{rule.rule_name}</span><span className="qc-rule-bar"><i style={{width:rule.share===null?'0%':rule.share+'%'}}/><b>{['NOT_EXECUTED','NOT_EVALUATED','NO_DATA'].includes(rule.state)?'—':qcNumber(rule.anomaly_count)}</b></span><span className="qc-state unknown">{qcPercent(rule.share)}</span></button>{open===rule.rule_id&&<div className="qc-rule-detail"><strong>{rule.rule_id} · {rule.rule_version}</strong><p>{rule.rule_type} · 평가 {qcNumber(rule.evaluated_count)}건 · 상태 {qcStateLabel(rule.state)}</p><p>실제 Threshold·입력값·플래그는 후보 상세에서 확인합니다.</p></div>}</div>)}{!rules.length&&<p className="qc-empty">{packet?'선택 시간창의 Rule 결과 없음':'Rule 결과 조회 중'}</p>}</div><details className="qc-rule-detail"><summary>현재 등록된 Rule 정의 · {qcNumber(packet?.rule_qc_counts.registered_definition_count)}개</summary><p>현재 정의 목록은 선택 시간창의 실행 결과와 별도입니다.</p><ul>{packet?.rule_qc_counts.registered_definitions?.map(rule=><li key={rule.rule_id+rule.rule_version}>{rule.rule_name} · {rule.rule_version} · {rule.active?'활성 정의':'비활성 정의'}<small> ({rule.rule_id})</small></li>)}</ul>{packet?.rule_qc_counts.definitions_truncated&&<p>정의 목록 일부만 조회됨</p>}</details><p className="qc-panel-note">1차 QC는 실제 값과 저장된 Rule만 표시합니다. 결측을 예측값으로 채우지 않습니다.</p></section>;
}

export function QCDailyMatrix({packet,onSelect}:{packet:QCDailyOverview|null;onSelect:(station:string,item:string)=>void}){
 const [page,setPage]=useState(1),[itemPage,setItemPage]=useState(1),[focusIndex,setFocusIndex]=useState(0),ref=useRef<HTMLDivElement>(null),rows=packet?.station_variable_matrix||[];
 const stations=[...new Set(rows.map(row=>row.station_id))],items=[...new Set(rows.map(row=>row.variable_code))],stationSlice=qcPage(stations,page,8),itemSlice=qcPage(items,itemPage,6),flags=semanticFlags(packet);
 const cellFlag=(row:typeof rows[number])=>{const rank=['bad','suspect','missing','unknown','normal'] as (keyof QCDailyCounts)[];return rank.map(key=>({key,flag:flags.find(f=>f.key===key)?.flag,count:row.counts[key]})).find(f=>f.count>0&&f.flag)?.flag;};
 const move=(event:React.KeyboardEvent,index:number)=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(event.key))return;event.preventDefault();const buttons=Array.from(ref.current?.querySelectorAll<HTMLButtonElement>('button[data-qc-cell]')||[]),next=nextQCHeatmapCell(index,event.key,stationSlice.rows.length,itemSlice.rows.length,buttons.map(b=>!b.disabled));setFocusIndex(next);buttons[next]?.focus();};
 return <section className="qc-panel qc-matrix" aria-label="관측소별 항목 운영 품질 현황"><QCPanelHeading title="관측소 × 관측항목 품질 현황"><span className="qc-pill">{stations.length}개소 · {items.length}항목</span></QCPanelHeading><div className="qc-matrix-scroll" ref={ref}><table><thead><tr><th>관측소</th>{itemSlice.rows.map(item=><th key={item} title={item}>{observationItemLabel(item)}</th>)}</tr></thead><tbody>{stationSlice.rows.map((station,rindex)=><tr key={station}><th title={station}>{rows.find(row=>row.station_id===station)?.station_name||station}</th>{itemSlice.rows.map((item,cindex)=>{const row=rows.find(r=>r.station_id===station&&r.variable_code===item),flag=row&&cellFlag(row),index=rindex*itemSlice.rows.length+cindex;const title=row?`${row.station_name} ${observationItemLabel(item)} · 총 ${row.total}건 · ${flags.map(f=>f.flag.label+' '+row.counts[f.key]).join(' · ')} · 최다 Rule ${row.top_rule||'없음'} · 최근 이상 ${row.recent_issue_time||'없음'}`:'선택 시간창에 자료 없음';return <td key={item}><button data-qc-cell disabled={!row} tabIndex={index===Math.min(focusIndex,stationSlice.rows.length*itemSlice.rows.length-1)?0:-1} onFocus={()=>setFocusIndex(index)} onKeyDown={e=>move(e,index)} onClick={()=>onSelect(station,item)} title={title} aria-label={title} style={{background:flag?flag.color+'40':'#eef3f9'}}>{row?flag?.label||'미평가':'—'}</button></td>;})}</tr>)}</tbody></table>{!rows.length&&<p className="qc-empty">{packet?'선택 시간창에 관측소·항목 자료 없음':'품질 행렬 조회 중'}</p>}</div><div className="qc-matrix-pagination"><nav aria-label="운영 행렬 관측소 페이지"><button aria-label="이전 운영 관측소" disabled={stationSlice.page<=1} onClick={()=>setPage(stationSlice.page-1)}><ChevronLeft size={12}/></button><span>{stationSlice.page}/{stationSlice.pages}</span><button aria-label="다음 운영 관측소" disabled={stationSlice.page>=stationSlice.pages} onClick={()=>setPage(stationSlice.page+1)}><ChevronRight size={12}/></button></nav><nav aria-label="운영 행렬 항목 페이지"><button aria-label="이전 운영 항목" disabled={itemSlice.page<=1} onClick={()=>setItemPage(itemSlice.page-1)}><ChevronLeft size={12}/></button><span>항목 {itemSlice.page}/{itemSlice.pages}</span><button aria-label="다음 운영 항목" disabled={itemSlice.page>=itemSlice.pages} onClick={()=>setItemPage(itemSlice.page+1)}><ChevronRight size={12}/></button></nav></div><div className="qc-chart-legend">{flags.map(f=><span key={f.key}><i style={{background:f.flag.color}}/>{f.flag.label}</span>)}</div><p className="qc-panel-note">셀 선택은 화면 전체를 같은 관측소·항목으로 필터합니다. Hover로 건수·Rule·최근 이상 시각을 확인하세요.</p></section>;
}
