import { useEffect, useState } from 'react';
import { Activity, Database, Server, Clock, Users, RefreshCw } from 'lucide-react';
import { API_BASE_URL, apiFetch } from '../api/client';
const panel='bg-white border border-blue-100 rounded-2xl p-5 shadow-sm min-w-0';
const labels:Record<string,string>={RESPONDING:'현재 응답',REACHABLE:'연결 확인',AVAILABLE:'조회 가능',CHECK_FAILED:'확인 실패'};
const stateColor=(s:string)=>s==='CHECK_FAILED'?'text-red-700 bg-red-50':'text-blue-700 bg-blue-50';
export default function ServiceWorkspace(){
 const [from,setFrom]=useState(()=>new Date(Date.now()-86400000).toISOString().slice(0,16)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,16));
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),[auto,setAuto]=useState(false),[latency,setLatency]=useState<number|null>(null);
 const [level,setLevel]=useState('전체'),[keyword,setKeyword]=useState('');
 useEffect(()=>{if(!auto)return;const id=setInterval(()=>{setTo(new Date().toISOString().slice(0,16));setRevision(v=>v+1);},60000);return()=>clearInterval(id);},[auto]);
 useEffect(()=>{const c=new AbortController();setData(null);setError('');setLatency(null);setLoading(true);if(from>to){setError('시작 시각은 종료 시각보다 늦을 수 없습니다.');setLoading(false);return()=>c.abort();}const start=performance.now();const q=new URLSearchParams({from_time:from+':00Z',to_time:to+':59Z'});apiFetch(`${API_BASE_URL}/service-monitoring/overview?${q}`,{signal:c.signal}).then(async r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(d=>{if(!c.signal.aborted){setData(d);setLatency(Math.round(performance.now()-start));}}).catch(e=>{if(!c.signal.aborted)setError(`서비스 점검 조회 실패: ${e.message}`);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[from,to,revision]);
 const logs=(data?.logs||[]).filter((l:any)=>(level==='전체'||l.issue_level===level)&&`${l.service_name} ${l.station_name} ${l.issue_detail}`.toLowerCase().includes(keyword.toLowerCase()));
 const failed=(data?.services||[]).filter((s:any)=>s.state==='CHECK_FAILED');
 return <div className="p-4 md:p-6 min-h-full space-y-5 bg-gradient-to-br from-blue-50/60 via-white to-indigo-50/40">
 <header className="flex flex-wrap justify-between items-end gap-4"><div><p className="text-xs font-bold text-blue-600 tracking-widest">SERVICE MONITORING</p><h1 className="text-3xl font-extrabold mt-2">서비스 모니터링</h1><p className="text-sm text-slate-500 mt-2">현재 연결 상태와 작업 원장, 업무 점검 기록을 함께 확인합니다.</p></div><div className="bg-blue-50 border border-blue-100 rounded-xl p-4 text-xs text-blue-800 max-w-sm"><Activity className="w-6 h-6 mb-2"/>실제 연결 확인 · AI 장애 예측 미평가<br/>단일 응답 성공은 기간 가동률이나 검색 정확도를 보증하지 않습니다.</div></header>
 <div className={`${panel} flex flex-wrap gap-3 text-xs items-end`}><label>업무 기록 시작 (UTC)<input type="datetime-local" value={from} onChange={e=>e.target.value&&setFrom(e.target.value)} className="block border rounded-lg p-2 mt-1"/></label><label>종료 (UTC)<input type="datetime-local" value={to} onChange={e=>e.target.value&&setTo(e.target.value)} className="block border rounded-lg p-2 mt-1"/></label><button onClick={()=>{setTo(new Date().toISOString().slice(0,16));setRevision(v=>v+1);}} className="bg-blue-600 rounded-lg px-4 py-2 text-white">현재 점검</button><label className="p-2"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> 1분 자동 갱신</label><span className="text-slate-500">연결 점검은 현재 시각 · 기록만 선택 기간 적용</span></div>
 {loading&&<p role="status" className="text-blue-600 text-sm">서비스와 작업 원장을 점검하고 있습니다…</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}
 <div className="grid grid-cols-2 xl:grid-cols-6 gap-3">{[['이번 조회 응답',latency==null?'—':`${latency} ms`,'복합 점검 API · 이번 1회',Activity],['서비스 가동률','미산정','기간별 상태 수집 필요',Server],['요청 오류율','미산정','전체 HTTP 요청 원장 필요',Clock],['연결 확인',data?`${data.services.length-failed.length}/${data.services.length}`:'—','현재 조회한 서비스만',Database],['배치 원장',data?`${data.batches.length}개`:'—','실행·완료는 아래 개별 확인',RefreshCw],['사용자 접속 수','미집계','접속 세션 원장 미연결',Users]].map(([t,v,n,Icon]:any)=><section className={panel} key={t}><Icon className="w-6 h-6 text-blue-600 mb-3"/><h2 className="text-xs font-bold">{t}</h2><p className="text-2xl font-extrabold my-2">{v}</p><p className="text-[11px] text-slate-500">{n}</p></section>)}</div>
 <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
 <section className={panel}><h2 className="font-bold mb-4">서비스 의존성과 현재 상태</h2><div className="text-center rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-800">브라우저 → 로컬 웹 → 데이터 API</div><p className="text-center text-blue-400 py-2">↓</p><div className="grid grid-cols-2 gap-3">{(data?.services||[]).map((s:any)=><div key={s.id} className="border border-blue-100 rounded-xl p-3 text-xs"><Server className="w-5 h-5 text-blue-600 mb-2"/><h3 className="font-bold">{s.name}</h3><p className={`inline-block rounded px-2 py-1 my-2 ${stateColor(s.state)}`}>{labels[s.state]||s.state}</p><p className="text-slate-500 break-words">{s.basis}</p></div>)}</div><p className="text-xs text-slate-500 mt-4">OSM 외부 타일·AI 추론·보고서 생성의 가동 상태는 이 점검에 포함되지 않습니다.</p></section>
 <section className={panel}><h2 className="font-bold mb-4">최근 업무 점검 타임라인</h2><p className="text-xs text-slate-500 mb-3">자동 서비스 이벤트 스트림과 별도 · 선택 기간의 최근 기록</p><div className="space-y-4 max-h-96 overflow-auto">{logs.slice(0,8).map((l:any)=><article key={l.service_log_id} className="border-l-2 border-blue-200 pl-3 text-xs"><p className="font-bold text-blue-800">{l.check_time} · {l.issue_level}</p><p className="font-semibold mt-1">{l.service_name} · {l.station_name}</p><p className="text-slate-500 mt-2">{l.issue_detail}</p></article>)}{data&&!logs.length&&<p className="text-sm text-slate-500">선택 범위의 업무 기록 없음 · 서비스 정상 판정 아님</p>}</div></section>
 <section className={panel}><h2 className="font-bold mb-4">서비스별 점검 결과</h2>{(data?.services||[]).map((s:any)=><div key={s.id} className="py-3 border-b border-slate-100 text-xs"><div className="flex justify-between gap-2"><strong>{s.name}</strong><span className={stateColor(s.state)+' px-2 rounded'}>{labels[s.state]||s.state}</span></div><p className="text-slate-500 mt-2">{s.latency_ms==null?'응답시간 미측정':`${s.latency_ms} ms · 이번 1회`}</p></div>)}<p className="text-xs text-slate-500 mt-4">확인 시각 {data?.checked_at||'미확인'}</p><p className="text-xs text-slate-500 mt-2">{data?.note}</p></section>
 </div>
 <section className={panel}><h2 className="font-bold mb-4">수집·문서·이전 배치 상태</h2><div className="overflow-auto"><table className="w-full text-xs text-left min-w-[850px]"><thead className="bg-blue-50"><tr>{['작업','원장 상태','진척 기록','원장 갱신 (UTC)','프로세스 확인','근거'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{(data?.batches||[]).map((b:any)=><tr key={b.name} className="border-b border-slate-100 align-top"><td className="p-3 font-bold">{b.name}</td><td className="p-3">{b.reported_state||b.status}<p className="text-[10px] text-amber-700 mt-1">원장 보고 상태</p></td><td className="p-3">{b.completed!=null?`${b.completed}/${b.total??'미확정'}`:'분모 별도 원장'}<p>{b.scope}</p></td><td className="p-3">{b.reported_at||'미확정'}<p className="text-slate-500 mt-1">{b.age_seconds!=null?`${b.age_seconds.toLocaleString()}초 전 기록`:''}</p></td><td className="p-3">{b.pid?`PID ${b.pid} · `:''}{b.process.state}<p className="text-slate-500 mt-1">{b.process.started_at||''}</p>{b.process.start_matches===false&&<p className="text-red-700">시작시각 불일치 · PID 재사용 가능</p>}<p className="text-amber-700 mt-1">OS lock 미확인</p></td><td className="p-3"><details><summary className="cursor-pointer text-blue-700">원장 위치</summary><p className="max-w-xs break-all mt-2">{b.source_path}</p></details></td></tr>)}</tbody></table></div><p className="text-xs text-slate-500 mt-3">{data?.batch_note}</p></section>
 <div className="grid grid-cols-1 xl:grid-cols-3 gap-4"><section className={`${panel} xl:col-span-2`}><div className="flex flex-wrap justify-between gap-3 mb-3"><h2 className="font-bold">업무 점검 기록</h2><div className="flex gap-2 text-xs"><input aria-label="기록 검색" placeholder="서비스·관측소·내용 검색" value={keyword} onChange={e=>setKeyword(e.target.value)} className="border rounded-lg p-2"/><select aria-label="기록 등급" value={level} onChange={e=>setLevel(e.target.value)} className="border rounded-lg p-2"><option>전체</option>{Object.keys(data?.level_counts||{}).map(l=><option key={l}>{l}</option>)}</select></div></div><div className="max-h-80 overflow-auto"><table className="w-full text-xs text-left"><thead className="bg-blue-50"><tr>{['시각 (UTC)','서비스/관측소','등급','내용'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{logs.map((l:any)=><tr key={l.service_log_id} className="border-b border-slate-100"><td className="p-2">{l.check_time}</td><td className="p-2">{l.service_name}<p className="text-slate-500">{l.station_name}</p></td><td className="p-2">{l.issue_level}</td><td className="p-2">{l.issue_detail}</td></tr>)}</tbody></table></div><p className="text-xs text-slate-500 mt-3">표시 {logs.length} / 서버 반환 {data?.logs.length??'—'} / 기간 전체 {data?.log_count??'미확정'}건 · {data?.log_state}</p><p className="text-xs text-slate-500 mt-2">{data?.log_note}</p></section><section className={panel}><h2 className="font-bold mb-4">확인 실패와 업무 기록 등급</h2><div className="bg-red-50 text-red-800 rounded-xl p-4"><p className="font-bold">현재 연결 확인 실패 {data?failed.length:'—'}건</p><p className="text-xs mt-2">{failed.map((s:any)=>s.name).join(', ')||'실패가 없더라도 전체 서비스의 무장애를 보증하지 않습니다.'}</p></div><div className="mt-4 space-y-2">{Object.entries(data?.level_counts||{}).map(([key,value])=><p className="flex justify-between text-xs rounded-lg bg-slate-50 p-3" key={key}><span>{key} 업무 기록</span><strong>{String(value)}건</strong></p>)}</div><p className="text-xs text-slate-500 mt-4">웹 로그·트레이스·해역별 서비스 SLA는 아직 통합 수집되지 않았습니다.</p></section></div>
 </div>;
}
