import {useEffect,useState} from 'react';
import {API_BASE_URL,apiFetch} from '../api/client';
import {trainingReviewMatches,type TrainingReview} from '../data/developmentReview';
import InputPreparationReview from './InputPreparationReview';

type Manifest={path:string;name:string;sha256?:string;domain?:string;item_id?:string;task?:string;unit?:string;status:string;blocker?:string};
const splits=['TRAIN','VALIDATION','TEST'];
async function read(path:string,init?:RequestInit){const response=await apiFetch(`${API_BASE_URL}${path}`,init);const data=await response.json();if(!response.ok){const detail=data.detail;throw new Error(typeof detail==='string'?detail:detail?.code||`HTTP ${response.status}`);}return data;}
export default function TrainingWorkbench({workerConfigured,models}:{workerConfigured:boolean;models:{version:string;name:string}[]}){
  const [manifests,setManifests]=useState<Manifest[]>([]),[selected,setSelected]=useState(''),[review,setReview]=useState<TrainingReview|null>(null);
  const [datasets,setDatasets]=useState<any[]>([]),[selection,setSelection]=useState<Record<string,string>>({}),[jobs,setJobs]=useState<any[]>([]);
  const [role,setRole]=useState(''),[authority,setAuthority]=useState('담당자 권한 미확인'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[revision,setRevision]=useState(0),[base,setBase]=useState('');
  const [inventory,setInventory]=useState<any>(null),[inventoryError,setInventoryError]=useState('');
  useEffect(()=>{const control=new AbortController();setError('');setReview(null);
    Promise.all([read('/model-development/training-manifests',{signal:control.signal}),read('/datasets',{signal:control.signal}),read('/mlops/training/jobs',{signal:control.signal})]).then(([catalog,rows,queue])=>{
      if(!Array.isArray(catalog.manifests)||!Array.isArray(rows)||!Array.isArray(queue.jobs))throw new Error('입력 검토 응답 형식 미확인');
      if(!control.signal.aborted){setManifests(catalog.manifests);setDatasets(rows);setJobs(queue.jobs);}})
      .catch(reason=>{if(!control.signal.aborted){setManifests([]);setDatasets([]);setJobs([]);setError(`학습 입력 조회 실패: ${reason.message}`);}});
    read('/session',{signal:control.signal}).then(value=>{if(!control.signal.aborted){setRole(value.role);setAuthority(`${value.user_id} · ${value.role}`);}}).catch(()=>{if(!control.signal.aborted){setRole('');setAuthority('담당자 연결 필요 · 계정 설정은 운영 시점에 수행');}});
    read('/model-development/task-readiness',{signal:control.signal}).then(value=>{if(!Array.isArray(value.rows)||value.task_keys!==value.rows.length)throw new Error('업무별 원장 응답 형식 미확인');if(!control.signal.aborted){setInventory(value);setInventoryError('');}}).catch(reason=>{if(!control.signal.aborted){setInventory(null);setInventoryError(`업무별 원천 검토 조회 실패: ${reason.message}`);}});
    return()=>control.abort();},[revision]);
  const manifest=manifests.find(m=>m.path===selected),canWrite=['operator','reviewer','admin'].includes(role);
  const reviewReady=trainingReviewMatches(review,manifest);
  const inspect=async()=>{if(!manifest?.sha256)return;setBusy(true);setReview(null);setError('');setNote('');try{setReview(await read(`/model-development/training-preflight?${new URLSearchParams({manifest_path:manifest.path,expected_sha256:manifest.sha256})}`));}catch(reason){setError(reason instanceof Error?reason.message:'입력 검증 실패');}finally{setBusy(false);}};
  const create=async()=>{setBusy(true);setError('');setNote('');try{const result=await read('/model-development/training-manifests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataset_ids:selection})});setSelected(result.manifest_path);setNote('고정 입력 생성 완료 · 큐와 모델 등록은 생성하지 않았습니다.');setRevision(v=>v+1);}catch(reason){setError(reason instanceof Error?reason.message:'고정 입력 생성 실패');}finally{setBusy(false);}};
  const enqueue=async()=>{if(!reviewReady||!manifest||!canWrite||!workerConfigured)return;setBusy(true);setError('');setNote('');try{const body={manifest_path:manifest.path,expected_sha256:manifest.sha256,...(base?{model_id:base}:{})};const result=await read(base?'/mlops/retrain':'/mlops/training/enqueue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setNote(`큐 확인: ${result.job_id} · ${result.state}. 학습 종료·운영 선정·배포는 별도 검증입니다.`);setRevision(v=>v+1);}catch(reason){setReview(null);setError(reason instanceof Error?reason.message:'학습 큐 요청 실패');}finally{setBusy(false);}};
  return <section id="training-input-review" aria-label="고정 승인 학습 입력 선택" className="bg-white border border-blue-200 rounded-xl p-4 text-sm space-y-3">
    <div className="flex justify-between"><h3 className="font-bold">고정 학습 입력 선택·검증</h3><button disabled={busy} onClick={()=>setRevision(v=>v+1)} className="text-blue-700 disabled:text-slate-400">입력·권한 다시 확인</button></div>
    <p className="text-xs text-slate-600">원천 승인과 고정 TRAIN/VALIDATION/TEST·평가·수용 정책을 모두 검증합니다. 큐 완료 후에도 독립 검토·후보 등록·모델 및 배포 승인 절차가 필요합니다.</p>
    <p className="text-xs">{authority} · 학습 사용 {workerConfigured?'설정됨':'미설정'}</p>
    {error&&<p role="alert" className="text-red-700">{error}</p>}{note&&<p role="status" className="text-blue-800 break-all">{note}</p>}
    <InputPreparationReview datasets={datasets} canWrite={canWrite} onChanged={()=>setRevision(v=>v+1)}/>
    <details><summary className="cursor-pointer font-medium">승인 데이터셋으로 고정 입력 생성</summary><div className="grid md:grid-cols-3 gap-2 mt-2">{splits.map(split=><label className="text-xs" key={split}>{split}<select className="block w-full border rounded p-2 mt-1" value={selection[split]||''} onChange={e=>setSelection({...selection,[split]:e.target.value})}><option value="">명시적으로 선택</option>{datasets.filter(d=>d.dataset_split===split&&d.status==='APPROVED').map(d=><option value={d.dataset_id} key={d.dataset_id}>{d.dataset_name} · {d.dataset_version} ({d.dataset_id})</option>)}</select></label>)}</div><p className="text-xs text-slate-500 mt-2">승인 문자열만으로 생성되지 않습니다. 파일 해시·실제 최신 승인·원천 binding·정책 동등성을 서버에서 다시 검사합니다.</p><button className="border rounded px-3 py-2 mt-2 disabled:text-slate-400" disabled={busy||!canWrite||splits.some(s=>!selection[s])} onClick={create}>선택한 세 분할로 입력 생성</button></details>
    <div className="flex flex-wrap gap-2"><select aria-label="고정 학습 입력 명세" className="border rounded p-2 max-w-full" value={selected} onChange={e=>{setSelected(e.target.value);setReview(null);setNote('');}}><option value="">{manifests.length?'입력 명세 선택':'등록된 고정 입력 없음'}</option>{manifests.map(m=><option key={m.path} value={m.path} disabled={m.status==='INVALID'}>{m.item_id||m.name} · {m.task||m.status}</option>)}</select><button className="border rounded px-3 py-2 disabled:text-slate-400" disabled={busy||!manifest?.sha256} onClick={inspect}>학습 전 근거 검증</button><select aria-label="재학습 기준 모델 버전" value={base} className="border rounded p-2" onChange={e=>setBase(e.target.value)}><option value="">새 비교 후보</option>{models.map(m=><option key={m.version} value={m.version}>{m.name} · {m.version}</option>)}</select><button className="bg-blue-600 text-white rounded px-3 py-2 disabled:bg-slate-200 disabled:text-slate-500" disabled={busy||!reviewReady||!canWrite||!workerConfigured} onClick={enqueue}>{base?'검증된 입력으로 재학습 요청':'검증된 입력을 학습 큐에 요청'}</button></div>
    {manifest&&<p className="text-xs break-all text-slate-500">{manifest.domain} · {manifest.item_id} · {manifest.task} · {manifest.unit}<br/>입력 SHA {manifest.sha256}</p>}
    {review&&<div className="rounded bg-slate-50 p-3 text-xs"><p className="font-bold">{reviewReady?'입력 검증됨 · 요청 가능':'근거 부족 · 학습 차단'}</p>{review.blockers?.map((b,i)=><p className="mt-2 break-words" key={i}>{b.code} · {b.detail}</p>)}{review.origin_membership_sha256&&<p className="break-all mt-1">동일 origin/target 참여 SHA {review.origin_membership_sha256}</p>}</div>}
    {!manifests.length&&!error&&<p className="text-xs text-amber-800">평가 입력 미등록 · 승인 원천·라벨·Feature·고정 세 분할과 정책을 준비해야 합니다. 임의 비율 분할로 요청을 만들지 않습니다.</p>}
    <details><summary className="cursor-pointer font-medium">학습 큐 · {jobs.length}건 (최근 최대 100건)</summary>{jobs.length?jobs.map(job=><p className="text-xs break-all mt-2" key={job.job_id}>{job.state} · 시도 {job.attempts}/{job.max_attempts} · {job.job_id}{job.reason&&` · ${job.reason}`}</p>):<p className="text-xs mt-2">큐 작업 없음 · 학습 완료의 의미가 아닙니다.</p>}</details>
    <details><summary className="cursor-pointer font-medium">업무별 원천·학습 준비 원장</summary>{inventoryError?<p role="alert" className="text-xs text-red-700 mt-2">{inventoryError}</p>:!inventory?<p className="text-xs mt-2">원장 조회 중…</p>:<><p className="text-xs mt-2">{inventory.task_keys}개 업무 키 · 검증된 고정 입력이 있는 키 {inventory.training_ready_count}개. 6개 자료형 기준선은 업무 전체의 운영 적합성과 별도입니다. 원문 코드 후보는 의미·단위·물리 센서 승인이 아닙니다.</p><div className="overflow-auto max-h-80 mt-2"><table className="w-full text-xs min-w-[660px]"><thead><tr>{['업무/항목','자료형','원문 보유 후보','승인 입력','필수 근거'].map(s=><th className="p-2 text-left" key={s}>{s}</th>)}</tr></thead><tbody>{inventory.rows.map((row:any)=><tr className="border-t align-top" key={`${row.domain}/${row.item_id}/${row.task}`}><td className="p-2">{row.domain} · {row.item_id}<br/>{row.task}</td><td className="p-2">{row.quantity_kind}</td><td className="p-2">{row.raw_grain_count}개 grain · {row.raw_held_rows?.toLocaleString()}행<br/>미승인 발견 후보</td><td className="p-2">{row.training_ready===true?'고정 입력 검증됨':'준비 안 됨'}</td><td className="p-2"><details><summary className="cursor-pointer">확인 {row.blockers.length}개</summary>{row.blockers.map((b:string,i:number)=><p className="mt-1 break-all" key={i}>{b}</p>)}</details></td></tr>)}</tbody></table></div></>}</details>
  </section>;
}
